package net.minecraft.tags;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;

public final class BlockTags {
   public static final TagKey<Block> WOOL;
   public static final TagKey<Block> PLANKS;
   public static final TagKey<Block> STONE_BRICKS;
   public static final TagKey<Block> WOODEN_BUTTONS;
   public static final TagKey<Block> STONE_BUTTONS;
   public static final TagKey<Block> BUTTONS;
   public static final TagKey<Block> WOOL_CARPETS;
   public static final TagKey<Block> WOODEN_DOORS;
   public static final TagKey<Block> WOODEN_STAIRS;
   public static final TagKey<Block> WOODEN_SLABS;
   public static final TagKey<Block> WOODEN_FENCES;
   public static final TagKey<Block> FENCE_GATES;
   public static final TagKey<Block> WOODEN_PRESSURE_PLATES;
   public static final TagKey<Block> WOODEN_SHELVES;
   public static final TagKey<Block> DOORS;
   public static final TagKey<Block> SAPLINGS;
   public static final TagKey<Block> BAMBOO_BLOCKS;
   public static final TagKey<Block> PALE_OAK_LOGS;
   public static final TagKey<Block> JUNGLE_LOGS;
   public static final TagKey<Block> WART_BLOCKS;
   public static final TagKey<Block> LOGS;
   public static final TagKey<Block> SAND;
   public static final TagKey<Block> SLABS;
   public static final TagKey<Block> WALLS;
   public static final TagKey<Block> STAIRS;
   public static final TagKey<Block> ANVIL;
   public static final TagKey<Block> RAILS;
   public static final TagKey<Block> LEAVES;
   public static final TagKey<Block> WOODEN_TRAPDOORS;
   public static final TagKey<Block> TRAPDOORS;
   public static final TagKey<Block> SMALL_FLOWERS;
   public static final TagKey<Block> FLOWERS;
   public static final TagKey<Block> BEDS;
   public static final TagKey<Block> FENCES;
   public static final TagKey<Block> SOUL_FIRE_BASE_BLOCKS;
   public static final TagKey<Block> CANDLES;
   public static final TagKey<Block> DAMPENS_VIBRATIONS;
   public static final TagKey<Block> GOLD_ORES;
   public static final TagKey<Block> IRON_ORES;
   public static final TagKey<Block> COPPER_ORES;
   public static final TagKey<Block> ORES;
   public static final TagKey<Block> DIRT;
   public static final TagKey<Block> MUD;
   public static final TagKey<Block> MOSS_BLOCKS;
   public static final TagKey<Block> GRASS_BLOCKS;
   public static final TagKey<Block> TERRACOTTA;
   public static final TagKey<Block> GLAZED_TERRACOTTA;
   public static final TagKey<Block> CONCRETE;
   public static final TagKey<Block> CONCRETE_SLABS;
   public static final TagKey<Block> CONCRETE_STAIRS;
   public static final TagKey<Block> CONCRETE_POWDERS;
   public static final TagKey<Block> COMPLETES_FIND_TREE_TUTORIAL;
   public static final TagKey<Block> SHULKER_BOXES;
   public static final TagKey<Block> COPPER_CHESTS;
   public static final TagKey<Block> LIGHTNING_RODS;
   public static final TagKey<Block> COPPER;
   public static final TagKey<Block> CHAINS;
   public static final TagKey<Block> COPPER_GOLEM_STATUES;
   public static final TagKey<Block> LANTERNS;
   public static final TagKey<Block> BARS;
   public static final TagKey<Block> SKULLS;
   public static final TagKey<Block> WOOL_SLABS;
   public static final TagKey<Block> WOOL_STAIRS;
   public static final TagKey<Block> CEILING_HANGING_SIGNS;
   public static final TagKey<Block> STANDING_SIGNS;
   public static final TagKey<Block> BEE_ATTRACTIVE;
   public static final TagKey<Block> MOB_INTERACTABLE_DOORS;
   public static final TagKey<Block> PRESSURE_PLATES;
   public static final TagKey<Block> STONE_PRESSURE_PLATES;
   public static final TagKey<Block> OVERWORLD_NATURAL_LOGS;
   public static final TagKey<Block> BANNERS;
   public static final TagKey<Block> PIGLIN_REPELLENTS;
   public static final TagKey<Block> BADLANDS_TERRACOTTA;
   public static final TagKey<Block> FLOWER_POTS;
   public static final TagKey<Block> ENDERMAN_HOLDABLE;
   public static final TagKey<Block> ICE;
   public static final TagKey<Block> VALID_SPAWN;
   public static final TagKey<Block> IMPERMEABLE;
   public static final TagKey<Block> UNDERWATER_BONEMEALS;
   public static final TagKey<Block> CORAL_BLOCKS;
   public static final TagKey<Block> WALL_CORALS;
   public static final TagKey<Block> CORAL_PLANTS;
   public static final TagKey<Block> CORALS;
   public static final TagKey<Block> WALL_SIGNS;
   public static final TagKey<Block> SIGNS;
   public static final TagKey<Block> WALL_HANGING_SIGNS;
   public static final TagKey<Block> ALL_HANGING_SIGNS;
   public static final TagKey<Block> ALL_SIGNS;
   public static final TagKey<Block> DRAGON_IMMUNE;
   public static final TagKey<Block> DRAGON_TRANSPARENT;
   public static final TagKey<Block> WITHER_IMMUNE;
   public static final TagKey<Block> WITHER_SUMMON_BASE_BLOCKS;
   public static final TagKey<Block> BEEHIVES;
   public static final TagKey<Block> CROPS;
   public static final TagKey<Block> BEE_GROWABLES;
   public static final TagKey<Block> PORTALS;
   public static final TagKey<Block> FIRE;
   public static final TagKey<Block> NYLIUM;
   public static final TagKey<Block> BEACON_BASE_BLOCKS;
   public static final TagKey<Block> SOUL_SPEED_BLOCKS;
   public static final TagKey<Block> WALL_POST_OVERRIDE;
   public static final TagKey<Block> CLIMBABLE;
   public static final TagKey<Block> FALL_DAMAGE_RESETTING;
   public static final TagKey<Block> HOGLIN_REPELLENTS;
   public static final TagKey<Block> STRIDER_WARM_BLOCKS;
   public static final TagKey<Block> CAMPFIRES;
   public static final TagKey<Block> GUARDED_BY_PIGLINS;
   public static final TagKey<Block> PREVENT_MOB_SPAWNING_INSIDE;
   public static final TagKey<Block> UNSTABLE_BOTTOM_CENTER;
   public static final TagKey<Block> EDIBLE_FOR_SHEEP;
   public static final TagKey<Block> CAN_GLIDE_THROUGH;
   public static final TagKey<Block> CAUSES_PERIODIC_GEYSER_ERUPTIONS;
   public static final TagKey<Block> CAUSES_CONTINUOUS_GEYSER_ERUPTIONS;
   public static final TagKey<Block> NETHER_PORTAL_FRAME;
   public static final TagKey<Block> CONDUIT_EFFECT_BLOCK;
   public static final TagKey<Block> INFINIBURN_OVERWORLD;
   public static final TagKey<Block> INFINIBURN_NETHER;
   public static final TagKey<Block> INFINIBURN_END;
   public static final TagKey<Block> SUBSTRATE_OVERWORLD;
   public static final TagKey<Block> BASE_STONE_OVERWORLD;
   public static final TagKey<Block> STONE_ORE_REPLACEABLES;
   public static final TagKey<Block> HEIGHT_SPECIFIC_ORE_REPLACEABLES;
   public static final TagKey<Block> DEEPSLATE_ORE_REPLACEABLES;
   public static final TagKey<Block> BASE_STONE_NETHER;
   public static final TagKey<Block> BENEATH_TREE_PODZOL_REPLACEABLE;
   public static final TagKey<Block> BENEATH_BAMBOO_PODZOL_REPLACEABLE;
   public static final TagKey<Block> CANNOT_REPLACE_BELOW_TREE_TRUNK;
   public static final TagKey<Block> CANNOT_PLACE_BASALT_PILLAR_ON;
   public static final TagKey<Block> UNCARVABLE;
   public static final TagKey<Block> CANDLE_CAKES;
   public static final TagKey<Block> CAULDRONS;
   public static final TagKey<Block> CRYSTAL_SOUND_BLOCKS;
   public static final TagKey<Block> INSIDE_STEP_SOUND_BLOCKS;
   public static final TagKey<Block> COMBINATION_STEP_SOUND_BLOCKS;
   public static final TagKey<Block> CAMEL_SAND_STEP_SOUND_BLOCKS;
   public static final TagKey<Block> HAPPY_GHAST_AVOIDS;
   public static final TagKey<Block> OCCLUDES_VIBRATION_SIGNALS;
   public static final TagKey<Block> CUSHION_USES_COLLISION_SHAPE;
   public static final TagKey<Block> DRIPSTONE_REPLACEABLE;
   public static final TagKey<Block> SULFUR_SPIKE_REPLACEABLE;
   public static final TagKey<Block> CAVE_VINES;
   public static final TagKey<Block> MOSS_REPLACEABLE;
   public static final TagKey<Block> LUSH_GROUND_REPLACEABLE;
   public static final TagKey<Block> AZALEA_ROOT_REPLACEABLE;
   public static final TagKey<Block> ICE_SPIKE_REPLACEABLE;
   public static final TagKey<Block> FOREST_ROCK_CAN_PLACE_ON;
   public static final TagKey<Block> HUGE_BROWN_MUSHROOM_CAN_PLACE_ON;
   public static final TagKey<Block> HUGE_RED_MUSHROOM_CAN_PLACE_ON;
   public static final TagKey<Block> SNOW;
   public static final TagKey<Block> MINEABLE_WITH_AXE;
   public static final TagKey<Block> MINEABLE_WITH_HOE;
   public static final TagKey<Block> MINEABLE_WITH_PICKAXE;
   public static final TagKey<Block> MINEABLE_WITH_SHOVEL;
   public static final TagKey<Block> SWORD_EFFICIENT;
   public static final TagKey<Block> SWORD_INSTANTLY_MINES;
   public static final TagKey<Block> SHEARS_EXTREME_BREAKING_SPEED;
   public static final TagKey<Block> SHEARS_MAJOR_BREAKING_SPEED;
   public static final TagKey<Block> SHEARS_MINOR_BREAKING_SPEED;
   public static final TagKey<Block> TURNS_INTO_DIRT_PATH;
   public static final TagKey<Block> TURNS_INTO_FARMLAND;
   public static final TagKey<Block> NEEDS_DIAMOND_TOOL;
   public static final TagKey<Block> NEEDS_IRON_TOOL;
   public static final TagKey<Block> NEEDS_STONE_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_NETHERITE_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_DIAMOND_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_IRON_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_COPPER_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_STONE_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_GOLD_TOOL;
   public static final TagKey<Block> INCORRECT_FOR_WOODEN_TOOL;
   public static final TagKey<Block> FEATURES_CANNOT_REPLACE;
   public static final TagKey<Block> LAVA_POOL_STONE_CANNOT_REPLACE;
   public static final TagKey<Block> GEODE_INVALID_BLOCKS;
   public static final TagKey<Block> FROG_PREFER_JUMP_TO;
   public static final TagKey<Block> SCULK_GROWTH_INHIBITORS;
   public static final TagKey<Block> SCULK_REPLACEABLE;
   public static final TagKey<Block> SCULK_REPLACEABLE_WORLD_GEN;
   public static final TagKey<Block> ANCIENT_CITY_REPLACEABLE;
   public static final TagKey<Block> VIBRATION_RESONATORS;
   public static final TagKey<Block> ANIMALS_SPAWNABLE_ON;
   public static final TagKey<Block> ARMADILLO_SPAWNABLE_ON;
   public static final TagKey<Block> AXOLOTLS_SPAWNABLE_ON;
   public static final TagKey<Block> GOATS_SPAWNABLE_ON;
   public static final TagKey<Block> MOOSHROOMS_SPAWNABLE_ON;
   public static final TagKey<Block> PARROTS_SPAWNABLE_ON;
   public static final TagKey<Block> POLAR_BEARS_SPAWNABLE_ON_ALTERNATE;
   public static final TagKey<Block> RABBITS_SPAWNABLE_ON;
   public static final TagKey<Block> FOXES_SPAWNABLE_ON;
   public static final TagKey<Block> WOLVES_SPAWNABLE_ON;
   public static final TagKey<Block> FROGS_SPAWNABLE_ON;
   public static final TagKey<Block> BATS_SPAWNABLE_ON;
   public static final TagKey<Block> CAMELS_SPAWNABLE_ON;
   public static final TagKey<Block> AZALEA_GROWS_ON;
   public static final TagKey<Block> CONVERTIBLE_TO_MUD;
   public static final TagKey<Block> MANGROVE_LOGS_CAN_GROW_THROUGH;
   public static final TagKey<Block> MANGROVE_ROOTS_CAN_GROW_THROUGH;
   public static final TagKey<Block> SNAPS_GOAT_HORN;
   public static final TagKey<Block> REPLACEABLE_BY_TREES;
   public static final TagKey<Block> REPLACEABLE_BY_MUSHROOMS;
   public static final TagKey<Block> ENABLES_BUBBLE_COLUMN_DRAG_DOWN;
   public static final TagKey<Block> ENABLES_BUBBLE_COLUMN_PUSH_UP;
   public static final TagKey<Block> CATS_CAN_SIT_ON;
   public static final TagKey<Block> CATS_CAN_LIE_ON;
   public static final TagKey<Block> SPEEDS_UP_ZOMBIE_VILLAGER_CURING;
   public static final TagKey<Block> VILLAGERS_CAN_SLEEP_ON_BED;
   public static final TagKey<Block> VILLAGER_BABIES_CAN_JUMP_ON_BED;
   public static final TagKey<Block> SUPPORTS_VEGETATION;
   public static final TagKey<Block> SUPPORTS_DRY_VEGETATION;
   public static final TagKey<Block> SUPPORTS_CROPS;
   public static final TagKey<Block> SUPPORTS_STEM_CROPS;
   public static final TagKey<Block> SUPPORTS_STEM_FRUIT;
   public static final TagKey<Block> SUPPORTS_PUMPKIN_STEM;
   public static final TagKey<Block> SUPPORTS_MELON_STEM;
   public static final TagKey<Block> SUPPORTS_PUMPKIN_STEM_FRUIT;
   public static final TagKey<Block> SUPPORTS_MELON_STEM_FRUIT;
   public static final TagKey<Block> SUPPORTS_SUGAR_CANE;
   public static final TagKey<Block> SUPPORTS_SUGAR_CANE_ADJACENTLY;
   public static final TagKey<Block> SUPPORTS_BAMBOO;
   public static final TagKey<Block> SUPPORTS_SMALL_DRIPLEAF;
   public static final TagKey<Block> SUPPORTS_BIG_DRIPLEAF;
   public static final TagKey<Block> SUPPORTS_CACTUS;
   public static final TagKey<Block> SUPPORTS_CHORUS_PLANT;
   public static final TagKey<Block> SUPPORTS_CHORUS_FLOWER;
   public static final TagKey<Block> SUPPORTS_NETHER_SPROUTS;
   public static final TagKey<Block> SUPPORTS_AZALEA;
   public static final TagKey<Block> SUPPORTS_WARPED_FUNGUS;
   public static final TagKey<Block> SUPPORTS_CRIMSON_FUNGUS;
   public static final TagKey<Block> SUPPORTS_MANGROVE_PROPAGULE;
   public static final TagKey<Block> SUPPORTS_HANGING_MANGROVE_PROPAGULE;
   public static final TagKey<Block> SUPPORTS_NETHER_WART;
   public static final TagKey<Block> SUPPORTS_CRIMSON_ROOTS;
   public static final TagKey<Block> SUPPORTS_WARPED_ROOTS;
   public static final TagKey<Block> SUPPORTS_WITHER_ROSE;
   public static final TagKey<Block> SUPPORTS_COCOA;
   public static final TagKey<Block> SUPPORTS_LILY_PAD;
   public static final TagKey<Block> SUPPORTS_FROGSPAWN;
   public static final TagKey<Block> PREVENTS_NEARBY_LEAF_DECAY;
   public static final TagKey<Block> SUPPORT_OVERRIDE_CACTUS_FLOWER;
   public static final TagKey<Block> SUPPORT_OVERRIDE_SNOW_LAYER;
   public static final TagKey<Block> CANNOT_SUPPORT_SNOW_LAYER;
   public static final TagKey<Block> CANNOT_SUPPORT_SEAGRASS;
   public static final TagKey<Block> CANNOT_SUPPORT_KELP;
   public static final TagKey<Block> OVERRIDES_MUSHROOM_LIGHT_REQUIREMENT;
   public static final TagKey<Block> GROWS_CROPS;
   public static final TagKey<Block> INVALID_SPAWN_INSIDE;
   public static final TagKey<Block> SNIFFER_DIGGABLE_BLOCK;
   public static final TagKey<Block> SNIFFER_EGG_HATCH_BOOST;
   public static final TagKey<Block> TRAIL_RUINS_REPLACEABLE;
   public static final TagKey<Block> REPLACEABLE;
   public static final TagKey<Block> ENCHANTMENT_POWER_PROVIDER;
   public static final TagKey<Block> ENCHANTMENT_POWER_TRANSMITTER;
   public static final TagKey<Block> MAINTAINS_FARMLAND;
   public static final TagKey<Block> BLOCKS_WIND_CHARGE_EXPLOSIONS;
   public static final TagKey<Block> DOES_NOT_BLOCK_HOPPERS;
   public static final TagKey<Block> SUPPRESSES_BOUNCE;
   public static final TagKey<Block> TRIGGERS_AMBIENT_DESERT_SAND_BLOCK_SOUNDS;
   public static final TagKey<Block> TRIGGERS_AMBIENT_DESERT_DRY_VEGETATION_BLOCK_SOUNDS;
   public static final TagKey<Block> TRIGGERS_AMBIENT_DRIED_GHAST_BLOCK_SOUNDS;
   public static final TagKey<Block> REQUIRED_FOR_POPLAR_LEAF_AMBIENCE;
   public static final TagKey<Block> SPELEOTHEMS;
   public static final TagKey<Block> DANGEROUS_FOR_TELEPORTATION;
   public static final TagKey<Block> CAT_DOES_NOT_TELEPORT_TO;
   public static final TagKey<Block> ENDERMAN_DOES_NOT_TELEPORT_TO;
   public static final TagKey<Block> SHULKER_DOES_NOT_TELEPORT_TO;
   public static final TagKey<Block> CONSUMABLE_DOES_NOT_TELEPORT_TO;
   public static final TagKey<Block> FOX_IMMUNE_TO;
   public static final TagKey<Block> POLAR_BEAR_IMMUNE_TO;
   public static final TagKey<Block> SNOW_GOLEM_IMMUNE_TO;
   public static final TagKey<Block> STRAY_IMMUNE_TO;
   public static final TagKey<Block> WITHER_IMMUNE_TO;
   public static final TagKey<Block> WITHER_SKELETON_IMMUNE_TO;
   public static final TagKey<Block> DEFAULT_IMMUNE_TO;
   public static final TagKey<Block> BLOCKS_MOTION;
   public static final TagKey<Block> BLOCKS_MOTION_NO_LEAVES;
   public static final TagKey<Block> ENTITIES_CAN_TELEPORT_TO;
   public static final TagKey<Block> BLOCKS_DOLPHIN_JUMP;
   public static final TagKey<Block> ICE_MELTS_WHEN_DESTROYED_ABOVE;
   public static final TagKey<Block> CAUSES_SUFFOCATION;
   public static final TagKey<Block> BLOCKS_MOTION_IN_HEIGHTMAP;
   public static final TagKey<Block> BLOCKS_MOTION_IN_HEIGHTMAP_NO_LEAVES;
   public static final TagKey<Block> BLOCKS_LAVA_FIRE_SPREAD;
   public static final TagKey<Block> BLOCKS_FLUID_FLOW;
   public static final TagKey<Block> WASHED_AWAY_BY_FLUIDS;
   public static final TagKey<Block> AIR;

   private BlockTags() {
      super();
   }

   private static TagKey<Block> create(final String name) {
      return TagKey.<Block>create(Registries.BLOCK, Identifier.withDefaultNamespace(name));
   }

   static {
      WOOL = BlockItemTags.WOOL.block();
      PLANKS = BlockItemTags.PLANKS.block();
      STONE_BRICKS = BlockItemTags.STONE_BRICKS.block();
      WOODEN_BUTTONS = BlockItemTags.WOODEN_BUTTONS.block();
      STONE_BUTTONS = BlockItemTags.STONE_BUTTONS.block();
      BUTTONS = BlockItemTags.BUTTONS.block();
      WOOL_CARPETS = BlockItemTags.WOOL_CARPETS.block();
      WOODEN_DOORS = BlockItemTags.WOODEN_DOORS.block();
      WOODEN_STAIRS = BlockItemTags.WOODEN_STAIRS.block();
      WOODEN_SLABS = BlockItemTags.WOODEN_SLABS.block();
      WOODEN_FENCES = BlockItemTags.WOODEN_FENCES.block();
      FENCE_GATES = BlockItemTags.FENCE_GATES.block();
      WOODEN_PRESSURE_PLATES = BlockItemTags.WOODEN_PRESSURE_PLATES.block();
      WOODEN_SHELVES = BlockItemTags.WOODEN_SHELVES.block();
      DOORS = BlockItemTags.DOORS.block();
      SAPLINGS = BlockItemTags.SAPLINGS.block();
      BAMBOO_BLOCKS = BlockItemTags.BAMBOO_BLOCKS.block();
      PALE_OAK_LOGS = BlockItemTags.PALE_OAK_LOGS.block();
      JUNGLE_LOGS = BlockItemTags.JUNGLE_LOGS.block();
      WART_BLOCKS = BlockItemTags.WART_BLOCKS.block();
      LOGS = BlockItemTags.LOGS.block();
      SAND = BlockItemTags.SAND.block();
      SLABS = BlockItemTags.SLABS.block();
      WALLS = BlockItemTags.WALLS.block();
      STAIRS = BlockItemTags.STAIRS.block();
      ANVIL = BlockItemTags.ANVIL.block();
      RAILS = BlockItemTags.RAILS.block();
      LEAVES = BlockItemTags.LEAVES.block();
      WOODEN_TRAPDOORS = BlockItemTags.WOODEN_TRAPDOORS.block();
      TRAPDOORS = BlockItemTags.TRAPDOORS.block();
      SMALL_FLOWERS = BlockItemTags.SMALL_FLOWERS.block();
      FLOWERS = BlockItemTags.FLOWERS.block();
      BEDS = BlockItemTags.BEDS.block();
      FENCES = BlockItemTags.FENCES.block();
      SOUL_FIRE_BASE_BLOCKS = BlockItemTags.SOUL_FIRE_BASE_BLOCKS.block();
      CANDLES = BlockItemTags.CANDLES.block();
      DAMPENS_VIBRATIONS = BlockItemTags.DAMPENS_VIBRATIONS.block();
      GOLD_ORES = BlockItemTags.GOLD_ORES.block();
      IRON_ORES = BlockItemTags.IRON_ORES.block();
      COPPER_ORES = BlockItemTags.COPPER_ORES.block();
      ORES = BlockItemTags.ORES.block();
      DIRT = BlockItemTags.DIRT.block();
      MUD = BlockItemTags.MUD.block();
      MOSS_BLOCKS = BlockItemTags.MOSS_BLOCKS.block();
      GRASS_BLOCKS = BlockItemTags.GRASS_BLOCKS.block();
      TERRACOTTA = BlockItemTags.TERRACOTTA.block();
      GLAZED_TERRACOTTA = BlockItemTags.GLAZED_TERRACOTTA.block();
      CONCRETE = BlockItemTags.CONCRETE.block();
      CONCRETE_SLABS = BlockItemTags.CONCRETE_SLABS.block();
      CONCRETE_STAIRS = BlockItemTags.CONCRETE_STAIRS.block();
      CONCRETE_POWDERS = BlockItemTags.CONCRETE_POWDERS.block();
      COMPLETES_FIND_TREE_TUTORIAL = BlockItemTags.COMPLETES_FIND_TREE_TUTORIAL.block();
      SHULKER_BOXES = BlockItemTags.SHULKER_BOXES.block();
      COPPER_CHESTS = BlockItemTags.COPPER_CHESTS.block();
      LIGHTNING_RODS = BlockItemTags.LIGHTNING_RODS.block();
      COPPER = BlockItemTags.COPPER.block();
      CHAINS = BlockItemTags.CHAINS.block();
      COPPER_GOLEM_STATUES = BlockItemTags.COPPER_GOLEM_STATUES.block();
      LANTERNS = BlockItemTags.LANTERNS.block();
      BARS = BlockItemTags.BARS.block();
      SKULLS = BlockItemTags.SKULLS.block();
      WOOL_SLABS = BlockItemTags.WOOL_SLABS.block();
      WOOL_STAIRS = BlockItemTags.WOOL_STAIRS.block();
      CEILING_HANGING_SIGNS = BlockItemTags.HANGING_SIGNS.block();
      STANDING_SIGNS = BlockItemTags.SIGNS.block();
      BEE_ATTRACTIVE = BlockItemTags.BEE_FOOD.block();
      MOB_INTERACTABLE_DOORS = create("mob_interactable_doors");
      PRESSURE_PLATES = create("pressure_plates");
      STONE_PRESSURE_PLATES = create("stone_pressure_plates");
      OVERWORLD_NATURAL_LOGS = create("overworld_natural_logs");
      BANNERS = create("banners");
      PIGLIN_REPELLENTS = create("piglin_repellents");
      BADLANDS_TERRACOTTA = create("badlands_terracotta");
      FLOWER_POTS = create("flower_pots");
      ENDERMAN_HOLDABLE = create("enderman_holdable");
      ICE = create("ice");
      VALID_SPAWN = create("valid_spawn");
      IMPERMEABLE = create("impermeable");
      UNDERWATER_BONEMEALS = create("underwater_bonemeals");
      CORAL_BLOCKS = create("coral_blocks");
      WALL_CORALS = create("wall_corals");
      CORAL_PLANTS = create("coral_plants");
      CORALS = create("corals");
      WALL_SIGNS = create("wall_signs");
      SIGNS = create("signs");
      WALL_HANGING_SIGNS = create("wall_hanging_signs");
      ALL_HANGING_SIGNS = create("all_hanging_signs");
      ALL_SIGNS = create("all_signs");
      DRAGON_IMMUNE = create("dragon_immune");
      DRAGON_TRANSPARENT = create("dragon_transparent");
      WITHER_IMMUNE = create("wither_immune");
      WITHER_SUMMON_BASE_BLOCKS = create("wither_summon_base_blocks");
      BEEHIVES = create("beehives");
      CROPS = create("crops");
      BEE_GROWABLES = create("bee_growables");
      PORTALS = create("portals");
      FIRE = create("fire");
      NYLIUM = create("nylium");
      BEACON_BASE_BLOCKS = create("beacon_base_blocks");
      SOUL_SPEED_BLOCKS = create("soul_speed_blocks");
      WALL_POST_OVERRIDE = create("wall_post_override");
      CLIMBABLE = create("climbable");
      FALL_DAMAGE_RESETTING = create("fall_damage_resetting");
      HOGLIN_REPELLENTS = create("hoglin_repellents");
      STRIDER_WARM_BLOCKS = create("strider_warm_blocks");
      CAMPFIRES = create("campfires");
      GUARDED_BY_PIGLINS = create("guarded_by_piglins");
      PREVENT_MOB_SPAWNING_INSIDE = create("prevent_mob_spawning_inside");
      UNSTABLE_BOTTOM_CENTER = create("unstable_bottom_center");
      EDIBLE_FOR_SHEEP = create("edible_for_sheep");
      CAN_GLIDE_THROUGH = create("can_glide_through");
      CAUSES_PERIODIC_GEYSER_ERUPTIONS = create("causes_periodic_geyser_eruptions");
      CAUSES_CONTINUOUS_GEYSER_ERUPTIONS = create("causes_continuous_geyser_eruptions");
      NETHER_PORTAL_FRAME = create("nether_portal_frame");
      CONDUIT_EFFECT_BLOCK = create("conduit_effect_block");
      INFINIBURN_OVERWORLD = create("infiniburn_overworld");
      INFINIBURN_NETHER = create("infiniburn_nether");
      INFINIBURN_END = create("infiniburn_end");
      SUBSTRATE_OVERWORLD = create("substrate_overworld");
      BASE_STONE_OVERWORLD = create("base_stone_overworld");
      STONE_ORE_REPLACEABLES = create("stone_ore_replaceables");
      HEIGHT_SPECIFIC_ORE_REPLACEABLES = create("height_specific_ore_replaceables");
      DEEPSLATE_ORE_REPLACEABLES = create("deepslate_ore_replaceables");
      BASE_STONE_NETHER = create("base_stone_nether");
      BENEATH_TREE_PODZOL_REPLACEABLE = create("beneath_tree_podzol_replaceable");
      BENEATH_BAMBOO_PODZOL_REPLACEABLE = create("beneath_bamboo_podzol_replaceable");
      CANNOT_REPLACE_BELOW_TREE_TRUNK = create("cannot_replace_below_tree_trunk");
      CANNOT_PLACE_BASALT_PILLAR_ON = create("cannot_place_basalt_pillar_on");
      UNCARVABLE = create("uncarvable");
      CANDLE_CAKES = create("candle_cakes");
      CAULDRONS = create("cauldrons");
      CRYSTAL_SOUND_BLOCKS = create("crystal_sound_blocks");
      INSIDE_STEP_SOUND_BLOCKS = create("inside_step_sound_blocks");
      COMBINATION_STEP_SOUND_BLOCKS = create("combination_step_sound_blocks");
      CAMEL_SAND_STEP_SOUND_BLOCKS = create("camel_sand_step_sound_blocks");
      HAPPY_GHAST_AVOIDS = create("happy_ghast_avoids");
      OCCLUDES_VIBRATION_SIGNALS = create("occludes_vibration_signals");
      CUSHION_USES_COLLISION_SHAPE = create("cushion_uses_collision_shape");
      DRIPSTONE_REPLACEABLE = create("dripstone_replaceable_blocks");
      SULFUR_SPIKE_REPLACEABLE = create("sulfur_spike_replaceable_blocks");
      CAVE_VINES = create("cave_vines");
      MOSS_REPLACEABLE = create("moss_replaceable");
      LUSH_GROUND_REPLACEABLE = create("lush_ground_replaceable");
      AZALEA_ROOT_REPLACEABLE = create("azalea_root_replaceable");
      ICE_SPIKE_REPLACEABLE = create("ice_spike_replaceable");
      FOREST_ROCK_CAN_PLACE_ON = create("forest_rock_can_place_on");
      HUGE_BROWN_MUSHROOM_CAN_PLACE_ON = create("huge_brown_mushroom_can_place_on");
      HUGE_RED_MUSHROOM_CAN_PLACE_ON = create("huge_red_mushroom_can_place_on");
      SNOW = create("snow");
      MINEABLE_WITH_AXE = create("mineable/axe");
      MINEABLE_WITH_HOE = create("mineable/hoe");
      MINEABLE_WITH_PICKAXE = create("mineable/pickaxe");
      MINEABLE_WITH_SHOVEL = create("mineable/shovel");
      SWORD_EFFICIENT = create("sword_efficient");
      SWORD_INSTANTLY_MINES = create("sword_instantly_mines");
      SHEARS_EXTREME_BREAKING_SPEED = create("shears_extreme_breaking_speed");
      SHEARS_MAJOR_BREAKING_SPEED = create("shears_major_breaking_speed");
      SHEARS_MINOR_BREAKING_SPEED = create("shears_minor_breaking_speed");
      TURNS_INTO_DIRT_PATH = create("turns_into_dirt_path");
      TURNS_INTO_FARMLAND = create("turns_into_farmland");
      NEEDS_DIAMOND_TOOL = create("needs_diamond_tool");
      NEEDS_IRON_TOOL = create("needs_iron_tool");
      NEEDS_STONE_TOOL = create("needs_stone_tool");
      INCORRECT_FOR_NETHERITE_TOOL = create("incorrect_for_netherite_tool");
      INCORRECT_FOR_DIAMOND_TOOL = create("incorrect_for_diamond_tool");
      INCORRECT_FOR_IRON_TOOL = create("incorrect_for_iron_tool");
      INCORRECT_FOR_COPPER_TOOL = create("incorrect_for_copper_tool");
      INCORRECT_FOR_STONE_TOOL = create("incorrect_for_stone_tool");
      INCORRECT_FOR_GOLD_TOOL = create("incorrect_for_gold_tool");
      INCORRECT_FOR_WOODEN_TOOL = create("incorrect_for_wooden_tool");
      FEATURES_CANNOT_REPLACE = create("features_cannot_replace");
      LAVA_POOL_STONE_CANNOT_REPLACE = create("lava_pool_stone_cannot_replace");
      GEODE_INVALID_BLOCKS = create("geode_invalid_blocks");
      FROG_PREFER_JUMP_TO = create("frog_prefer_jump_to");
      SCULK_GROWTH_INHIBITORS = create("sculk_growth_inhibitors");
      SCULK_REPLACEABLE = create("sculk_replaceable");
      SCULK_REPLACEABLE_WORLD_GEN = create("sculk_replaceable_world_gen");
      ANCIENT_CITY_REPLACEABLE = create("ancient_city_replaceable");
      VIBRATION_RESONATORS = create("vibration_resonators");
      ANIMALS_SPAWNABLE_ON = create("animals_spawnable_on");
      ARMADILLO_SPAWNABLE_ON = create("armadillo_spawnable_on");
      AXOLOTLS_SPAWNABLE_ON = create("axolotls_spawnable_on");
      GOATS_SPAWNABLE_ON = create("goats_spawnable_on");
      MOOSHROOMS_SPAWNABLE_ON = create("mooshrooms_spawnable_on");
      PARROTS_SPAWNABLE_ON = create("parrots_spawnable_on");
      POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = create("polar_bears_spawnable_on_alternate");
      RABBITS_SPAWNABLE_ON = create("rabbits_spawnable_on");
      FOXES_SPAWNABLE_ON = create("foxes_spawnable_on");
      WOLVES_SPAWNABLE_ON = create("wolves_spawnable_on");
      FROGS_SPAWNABLE_ON = create("frogs_spawnable_on");
      BATS_SPAWNABLE_ON = create("bats_spawnable_on");
      CAMELS_SPAWNABLE_ON = create("camels_spawnable_on");
      AZALEA_GROWS_ON = create("azalea_grows_on");
      CONVERTIBLE_TO_MUD = create("convertible_to_mud");
      MANGROVE_LOGS_CAN_GROW_THROUGH = create("mangrove_logs_can_grow_through");
      MANGROVE_ROOTS_CAN_GROW_THROUGH = create("mangrove_roots_can_grow_through");
      SNAPS_GOAT_HORN = create("snaps_goat_horn");
      REPLACEABLE_BY_TREES = create("replaceable_by_trees");
      REPLACEABLE_BY_MUSHROOMS = create("replaceable_by_mushrooms");
      ENABLES_BUBBLE_COLUMN_DRAG_DOWN = create("enables_bubble_column_drag_down");
      ENABLES_BUBBLE_COLUMN_PUSH_UP = create("enables_bubble_column_push_up");
      CATS_CAN_SIT_ON = create("cats_can_sit_on");
      CATS_CAN_LIE_ON = create("cats_can_lie_on");
      SPEEDS_UP_ZOMBIE_VILLAGER_CURING = create("speeds_up_zombie_villager_curing");
      VILLAGERS_CAN_SLEEP_ON_BED = create("villagers_can_sleep_on_bed");
      VILLAGER_BABIES_CAN_JUMP_ON_BED = create("villager_babies_can_jump_on_bed");
      SUPPORTS_VEGETATION = create("supports_vegetation");
      SUPPORTS_DRY_VEGETATION = create("supports_dry_vegetation");
      SUPPORTS_CROPS = create("supports_crops");
      SUPPORTS_STEM_CROPS = create("supports_stem_crops");
      SUPPORTS_STEM_FRUIT = create("supports_stem_fruit");
      SUPPORTS_PUMPKIN_STEM = create("supports_pumpkin_stem");
      SUPPORTS_MELON_STEM = create("supports_melon_stem");
      SUPPORTS_PUMPKIN_STEM_FRUIT = create("supports_pumpkin_stem_fruit");
      SUPPORTS_MELON_STEM_FRUIT = create("supports_melon_stem_fruit");
      SUPPORTS_SUGAR_CANE = create("supports_sugar_cane");
      SUPPORTS_SUGAR_CANE_ADJACENTLY = create("supports_sugar_cane_adjacently");
      SUPPORTS_BAMBOO = create("supports_bamboo");
      SUPPORTS_SMALL_DRIPLEAF = create("supports_small_dripleaf");
      SUPPORTS_BIG_DRIPLEAF = create("supports_big_dripleaf");
      SUPPORTS_CACTUS = create("supports_cactus");
      SUPPORTS_CHORUS_PLANT = create("supports_chorus_plant");
      SUPPORTS_CHORUS_FLOWER = create("supports_chorus_flower");
      SUPPORTS_NETHER_SPROUTS = create("supports_nether_sprouts");
      SUPPORTS_AZALEA = create("supports_azalea");
      SUPPORTS_WARPED_FUNGUS = create("supports_warped_fungus");
      SUPPORTS_CRIMSON_FUNGUS = create("supports_crimson_fungus");
      SUPPORTS_MANGROVE_PROPAGULE = create("supports_mangrove_propagule");
      SUPPORTS_HANGING_MANGROVE_PROPAGULE = create("supports_hanging_mangrove_propagule");
      SUPPORTS_NETHER_WART = create("supports_nether_wart");
      SUPPORTS_CRIMSON_ROOTS = create("supports_crimson_roots");
      SUPPORTS_WARPED_ROOTS = create("supports_warped_roots");
      SUPPORTS_WITHER_ROSE = create("supports_wither_rose");
      SUPPORTS_COCOA = create("supports_cocoa");
      SUPPORTS_LILY_PAD = create("supports_lily_pad");
      SUPPORTS_FROGSPAWN = create("supports_frogspawn");
      PREVENTS_NEARBY_LEAF_DECAY = create("prevents_nearby_leaf_decay");
      SUPPORT_OVERRIDE_CACTUS_FLOWER = create("support_override_cactus_flower");
      SUPPORT_OVERRIDE_SNOW_LAYER = create("support_override_snow_layer");
      CANNOT_SUPPORT_SNOW_LAYER = create("cannot_support_snow_layer");
      CANNOT_SUPPORT_SEAGRASS = create("cannot_support_seagrass");
      CANNOT_SUPPORT_KELP = create("cannot_support_kelp");
      OVERRIDES_MUSHROOM_LIGHT_REQUIREMENT = create("overrides_mushroom_light_requirement");
      GROWS_CROPS = create("grows_crops");
      INVALID_SPAWN_INSIDE = create("invalid_spawn_inside");
      SNIFFER_DIGGABLE_BLOCK = create("sniffer_diggable_block");
      SNIFFER_EGG_HATCH_BOOST = create("sniffer_egg_hatch_boost");
      TRAIL_RUINS_REPLACEABLE = create("trail_ruins_replaceable");
      REPLACEABLE = create("replaceable");
      ENCHANTMENT_POWER_PROVIDER = create("enchantment_power_provider");
      ENCHANTMENT_POWER_TRANSMITTER = create("enchantment_power_transmitter");
      MAINTAINS_FARMLAND = create("maintains_farmland");
      BLOCKS_WIND_CHARGE_EXPLOSIONS = create("blocks_wind_charge_explosions");
      DOES_NOT_BLOCK_HOPPERS = create("does_not_block_hoppers");
      SUPPRESSES_BOUNCE = create("suppresses_bounce");
      TRIGGERS_AMBIENT_DESERT_SAND_BLOCK_SOUNDS = create("triggers_ambient_desert_sand_block_sounds");
      TRIGGERS_AMBIENT_DESERT_DRY_VEGETATION_BLOCK_SOUNDS = create("triggers_ambient_desert_dry_vegetation_block_sounds");
      TRIGGERS_AMBIENT_DRIED_GHAST_BLOCK_SOUNDS = create("triggers_ambient_dried_ghast_block_sounds");
      REQUIRED_FOR_POPLAR_LEAF_AMBIENCE = create("required_for_poplar_leaf_ambience");
      SPELEOTHEMS = create("speleothems");
      DANGEROUS_FOR_TELEPORTATION = create("dangerous_for_teleportation");
      CAT_DOES_NOT_TELEPORT_TO = create("cat_does_not_teleport_to");
      ENDERMAN_DOES_NOT_TELEPORT_TO = create("enderman_does_not_teleport_to");
      SHULKER_DOES_NOT_TELEPORT_TO = create("shulker_does_not_teleport_to");
      CONSUMABLE_DOES_NOT_TELEPORT_TO = create("consumable_does_not_teleport_to");
      FOX_IMMUNE_TO = create("fox_immune_to");
      POLAR_BEAR_IMMUNE_TO = create("polar_bear_immune_to");
      SNOW_GOLEM_IMMUNE_TO = create("snow_golem_immune_to");
      STRAY_IMMUNE_TO = create("stray_immune_to");
      WITHER_IMMUNE_TO = create("wither_immune_to");
      WITHER_SKELETON_IMMUNE_TO = create("wither_skeleton_immune_to");
      DEFAULT_IMMUNE_TO = create("default_immune_to");
      BLOCKS_MOTION = create("blocks_motion");
      BLOCKS_MOTION_NO_LEAVES = create("blocks_motion_no_leaves");
      ENTITIES_CAN_TELEPORT_TO = create("entities_can_teleport_to");
      BLOCKS_DOLPHIN_JUMP = create("blocks_dolphin_jump");
      ICE_MELTS_WHEN_DESTROYED_ABOVE = create("ice_melts_when_destroyed_above");
      CAUSES_SUFFOCATION = create("causes_suffocation");
      BLOCKS_MOTION_IN_HEIGHTMAP = create("blocks_motion_in_heightmap");
      BLOCKS_MOTION_IN_HEIGHTMAP_NO_LEAVES = create("blocks_motion_in_heightmap_no_leaves");
      BLOCKS_LAVA_FIRE_SPREAD = create("blocks_lava_fire_spread");
      BLOCKS_FLUID_FLOW = create("blocks_fluid_flow");
      WASHED_AWAY_BY_FLUIDS = create("washed_away_by_fluids");
      AIR = create("air");
   }
}
