package net.minecraft.tags;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;

public final class ItemTags {
   public static final TagKey<Item> WOOL;
   public static final TagKey<Item> PLANKS;
   public static final TagKey<Item> STONE_BRICKS;
   public static final TagKey<Item> WOODEN_BUTTONS;
   public static final TagKey<Item> WOOL_CARPETS;
   public static final TagKey<Item> WOODEN_DOORS;
   public static final TagKey<Item> WOODEN_STAIRS;
   public static final TagKey<Item> WOODEN_SLABS;
   public static final TagKey<Item> WOODEN_FENCES;
   public static final TagKey<Item> FENCE_GATES;
   public static final TagKey<Item> WOODEN_PRESSURE_PLATES;
   public static final TagKey<Item> WOODEN_SHELVES;
   public static final TagKey<Item> SAPLINGS;
   public static final TagKey<Item> BAMBOO_BLOCKS;
   public static final TagKey<Item> OAK_LOGS;
   public static final TagKey<Item> DARK_OAK_LOGS;
   public static final TagKey<Item> PALE_OAK_LOGS;
   public static final TagKey<Item> BIRCH_LOGS;
   public static final TagKey<Item> ACACIA_LOGS;
   public static final TagKey<Item> SPRUCE_LOGS;
   public static final TagKey<Item> MANGROVE_LOGS;
   public static final TagKey<Item> JUNGLE_LOGS;
   public static final TagKey<Item> CHERRY_LOGS;
   public static final TagKey<Item> CRIMSON_STEMS;
   public static final TagKey<Item> WARPED_STEMS;
   public static final TagKey<Item> WART_BLOCKS;
   public static final TagKey<Item> LOGS_THAT_BURN;
   public static final TagKey<Item> LOGS;
   public static final TagKey<Item> SAND;
   public static final TagKey<Item> SMELTS_TO_GLASS;
   public static final TagKey<Item> WALLS;
   public static final TagKey<Item> ANVIL;
   public static final TagKey<Item> RAILS;
   public static final TagKey<Item> LEAVES;
   public static final TagKey<Item> WOODEN_TRAPDOORS;
   public static final TagKey<Item> BEDS;
   public static final TagKey<Item> SOUL_FIRE_BASE_BLOCKS;
   public static final TagKey<Item> CANDLES;
   public static final TagKey<Item> DAMPENS_VIBRATIONS;
   public static final TagKey<Item> GOLD_ORES;
   public static final TagKey<Item> IRON_ORES;
   public static final TagKey<Item> DIAMOND_ORES;
   public static final TagKey<Item> REDSTONE_ORES;
   public static final TagKey<Item> LAPIS_ORES;
   public static final TagKey<Item> COAL_ORES;
   public static final TagKey<Item> EMERALD_ORES;
   public static final TagKey<Item> COPPER_ORES;
   public static final TagKey<Item> DIRT;
   public static final TagKey<Item> MUD;
   public static final TagKey<Item> MOSS_BLOCKS;
   public static final TagKey<Item> TERRACOTTA;
   public static final TagKey<Item> GLAZED_TERRACOTTA;
   public static final TagKey<Item> CONCRETE;
   public static final TagKey<Item> CONCRETE_POWDERS;
   public static final TagKey<Item> COMPLETES_FIND_TREE_TUTORIAL;
   public static final TagKey<Item> SHULKER_BOXES;
   public static final TagKey<Item> COPPER;
   public static final TagKey<Item> SIGNS;
   public static final TagKey<Item> HANGING_SIGNS;
   public static final TagKey<Item> BEE_FOOD;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_BOUNCY;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_REGULAR;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_SLOW_FLAT;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_FAST_FLAT;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_LIGHT;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_FAST_SLIDING;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_SLOW_SLIDING;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_STICKY;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_HIGH_RESISTANCE;
   public static final TagKey<Item> SULFUR_CUBE_ARCHETYPE_EXPLOSIVE;
   public static final TagKey<Item> SULFUR_CUBE_SWALLOWABLE;
   public static final TagKey<Item> BANNERS;
   public static final TagKey<Item> PIGLIN_REPELLENTS;
   public static final TagKey<Item> PIGLIN_LOVED;
   public static final TagKey<Item> IGNORED_BY_PIGLIN_BABIES;
   public static final TagKey<Item> PIGLIN_SAFE_ARMOR;
   public static final TagKey<Item> DUPLICATES_ALLAYS;
   public static final TagKey<Item> BREWING_FUEL;
   public static final TagKey<Item> EGGS;
   public static final TagKey<Item> MEAT;
   public static final TagKey<Item> SNIFFER_FOOD;
   public static final TagKey<Item> PIGLIN_FOOD;
   public static final TagKey<Item> FOX_FOOD;
   public static final TagKey<Item> COW_FOOD;
   public static final TagKey<Item> GOAT_FOOD;
   public static final TagKey<Item> SHEEP_FOOD;
   public static final TagKey<Item> WOLF_FOOD;
   public static final TagKey<Item> CAT_FOOD;
   public static final TagKey<Item> HORSE_FOOD;
   public static final TagKey<Item> ZOMBIE_HORSE_FOOD;
   public static final TagKey<Item> HORSE_TEMPT_ITEMS;
   public static final TagKey<Item> HARNESSES;
   public static final TagKey<Item> HAPPY_GHAST_FOOD;
   public static final TagKey<Item> HAPPY_GHAST_TEMPT_ITEMS;
   public static final TagKey<Item> CAMEL_FOOD;
   public static final TagKey<Item> CAMEL_HUSK_FOOD;
   public static final TagKey<Item> ARMADILLO_FOOD;
   public static final TagKey<Item> CHICKEN_FOOD;
   public static final TagKey<Item> FROG_FOOD;
   public static final TagKey<Item> HOGLIN_FOOD;
   public static final TagKey<Item> LLAMA_FOOD;
   public static final TagKey<Item> LLAMA_TEMPT_ITEMS;
   public static final TagKey<Item> OCELOT_FOOD;
   public static final TagKey<Item> PANDA_FOOD;
   public static final TagKey<Item> PANDA_EATS_FROM_GROUND;
   public static final TagKey<Item> PIG_FOOD;
   public static final TagKey<Item> RABBIT_FOOD;
   public static final TagKey<Item> STRIDER_FOOD;
   public static final TagKey<Item> STRIDER_TEMPT_ITEMS;
   public static final TagKey<Item> TURTLE_FOOD;
   public static final TagKey<Item> PARROT_FOOD;
   public static final TagKey<Item> PARROT_POISONOUS_FOOD;
   public static final TagKey<Item> AXOLOTL_FOOD;
   public static final TagKey<Item> NAUTILUS_BUCKET_FOOD;
   public static final TagKey<Item> NAUTILUS_FOOD;
   public static final TagKey<Item> NAUTILUS_TAMING_ITEMS;
   public static final TagKey<Item> SULFUR_CUBE_FOOD;
   public static final TagKey<Item> NON_FLAMMABLE_WOOD;
   public static final TagKey<Item> BOATS;
   public static final TagKey<Item> CHEST_BOATS;
   public static final TagKey<Item> FISHES;
   public static final TagKey<Item> CREEPER_DROP_MUSIC_DISCS;
   public static final TagKey<Item> COALS;
   public static final TagKey<Item> ARROWS;
   public static final TagKey<Item> LECTERN_BOOKS;
   public static final TagKey<Item> BOOKSHELF_BOOKS;
   public static final TagKey<Item> BEACON_PAYMENT_ITEMS;
   public static final TagKey<Item> WOODEN_TOOL_MATERIALS;
   public static final TagKey<Item> STONE_TOOL_MATERIALS;
   public static final TagKey<Item> COPPER_TOOL_MATERIALS;
   public static final TagKey<Item> IRON_TOOL_MATERIALS;
   public static final TagKey<Item> GOLD_TOOL_MATERIALS;
   public static final TagKey<Item> DIAMOND_TOOL_MATERIALS;
   public static final TagKey<Item> NETHERITE_TOOL_MATERIALS;
   public static final TagKey<Item> REPAIRS_LEATHER_ARMOR;
   public static final TagKey<Item> REPAIRS_COPPER_ARMOR;
   public static final TagKey<Item> REPAIRS_CHAIN_ARMOR;
   public static final TagKey<Item> REPAIRS_IRON_ARMOR;
   public static final TagKey<Item> REPAIRS_GOLD_ARMOR;
   public static final TagKey<Item> REPAIRS_DIAMOND_ARMOR;
   public static final TagKey<Item> REPAIRS_NETHERITE_ARMOR;
   public static final TagKey<Item> REPAIRS_TURTLE_HELMET;
   public static final TagKey<Item> REPAIRS_WOLF_ARMOR;
   public static final TagKey<Item> STONE_CRAFTING_MATERIALS;
   public static final TagKey<Item> FREEZE_IMMUNE_WEARABLES;
   public static final TagKey<Item> CLUSTER_MAX_HARVESTABLES;
   public static final TagKey<Item> COMPASSES;
   public static final TagKey<Item> CREEPER_IGNITERS;
   public static final TagKey<Item> NOTE_BLOCK_TOP_INSTRUMENTS;
   public static final TagKey<Item> FOOT_ARMOR;
   public static final TagKey<Item> LEG_ARMOR;
   public static final TagKey<Item> CHEST_ARMOR;
   public static final TagKey<Item> HEAD_ARMOR;
   public static final TagKey<Item> SKULLS;
   public static final TagKey<Item> TRIMMABLE_ARMOR;
   public static final TagKey<Item> TRIM_MATERIALS;
   public static final TagKey<Item> DECORATED_POT_SHERDS;
   public static final TagKey<Item> DECORATED_POT_INGREDIENTS;
   public static final TagKey<Item> SWORDS;
   public static final TagKey<Item> AXES;
   public static final TagKey<Item> HOES;
   public static final TagKey<Item> PICKAXES;
   public static final TagKey<Item> SHOVELS;
   public static final TagKey<Item> SPEARS;
   public static final TagKey<Item> BREAKS_DECORATED_POTS;
   public static final TagKey<Item> VILLAGER_PLANTABLE_SEEDS;
   public static final TagKey<Item> VILLAGER_PICKS_UP;
   public static final TagKey<Item> FURNACE_MINECART_FUEL;
   public static final TagKey<Item> BUNDLES;
   public static final TagKey<Item> BOOK_CLONING_TARGET;
   public static final TagKey<Item> DYES;
   public static final TagKey<Item> LOOM_DYES;
   public static final TagKey<Item> LOOM_PATTERNS;
   public static final TagKey<Item> CAULDRON_CAN_REMOVE_DYE;
   public static final TagKey<Item> CAT_COLLAR_DYES;
   public static final TagKey<Item> WOLF_COLLAR_DYES;
   public static final TagKey<Item> SKELETON_PREFERRED_WEAPONS;
   public static final TagKey<Item> DROWNED_PREFERRED_WEAPONS;
   public static final TagKey<Item> PIGLIN_PREFERRED_WEAPONS;
   public static final TagKey<Item> PILLAGER_PREFERRED_WEAPONS;
   public static final TagKey<Item> WITHER_SKELETON_DISLIKED_WEAPONS;
   public static final TagKey<Item> SHEARABLE_FROM_COPPER_GOLEM;
   public static final TagKey<Item> METAL_NUGGETS;
   public static final TagKey<Item> FOOT_ARMOR_ENCHANTABLE;
   public static final TagKey<Item> LEG_ARMOR_ENCHANTABLE;
   public static final TagKey<Item> CHEST_ARMOR_ENCHANTABLE;
   public static final TagKey<Item> HEAD_ARMOR_ENCHANTABLE;
   public static final TagKey<Item> ARMOR_ENCHANTABLE;
   public static final TagKey<Item> MELEE_WEAPON_ENCHANTABLE;
   public static final TagKey<Item> SWEEPING_ENCHANTABLE;
   public static final TagKey<Item> FIRE_ASPECT_ENCHANTABLE;
   public static final TagKey<Item> SHARP_WEAPON_ENCHANTABLE;
   public static final TagKey<Item> WEAPON_ENCHANTABLE;
   public static final TagKey<Item> MINING_ENCHANTABLE;
   public static final TagKey<Item> MINING_LOOT_ENCHANTABLE;
   public static final TagKey<Item> FISHING_ENCHANTABLE;
   public static final TagKey<Item> TRIDENT_ENCHANTABLE;
   public static final TagKey<Item> LUNGE_ENCHANTABLE;
   public static final TagKey<Item> DURABILITY_ENCHANTABLE;
   public static final TagKey<Item> BOW_ENCHANTABLE;
   public static final TagKey<Item> EQUIPPABLE_ENCHANTABLE;
   public static final TagKey<Item> CROSSBOW_ENCHANTABLE;
   public static final TagKey<Item> VANISHING_ENCHANTABLE;
   public static final TagKey<Item> MACE_ENCHANTABLE;
   public static final TagKey<Item> MAP_INVISIBILITY_EQUIPMENT;
   public static final TagKey<Item> GAZE_DISGUISE_EQUIPMENT;

   private ItemTags() {
      super();
   }

   private static TagKey<Item> bind(final String name) {
      return TagKey.<Item>create(Registries.ITEM, Identifier.withDefaultNamespace(name));
   }

   static {
      WOOL = BlockItemTags.WOOL.item();
      PLANKS = BlockItemTags.PLANKS.item();
      STONE_BRICKS = BlockItemTags.STONE_BRICKS.item();
      WOODEN_BUTTONS = BlockItemTags.WOODEN_BUTTONS.item();
      WOOL_CARPETS = BlockItemTags.WOOL_CARPETS.item();
      WOODEN_DOORS = BlockItemTags.WOODEN_DOORS.item();
      WOODEN_STAIRS = BlockItemTags.WOODEN_STAIRS.item();
      WOODEN_SLABS = BlockItemTags.WOODEN_SLABS.item();
      WOODEN_FENCES = BlockItemTags.WOODEN_FENCES.item();
      FENCE_GATES = BlockItemTags.FENCE_GATES.item();
      WOODEN_PRESSURE_PLATES = BlockItemTags.WOODEN_PRESSURE_PLATES.item();
      WOODEN_SHELVES = BlockItemTags.WOODEN_SHELVES.item();
      SAPLINGS = BlockItemTags.SAPLINGS.item();
      BAMBOO_BLOCKS = BlockItemTags.BAMBOO_BLOCKS.item();
      OAK_LOGS = BlockItemTags.OAK_LOGS.item();
      DARK_OAK_LOGS = BlockItemTags.DARK_OAK_LOGS.item();
      PALE_OAK_LOGS = BlockItemTags.PALE_OAK_LOGS.item();
      BIRCH_LOGS = BlockItemTags.BIRCH_LOGS.item();
      ACACIA_LOGS = BlockItemTags.ACACIA_LOGS.item();
      SPRUCE_LOGS = BlockItemTags.SPRUCE_LOGS.item();
      MANGROVE_LOGS = BlockItemTags.MANGROVE_LOGS.item();
      JUNGLE_LOGS = BlockItemTags.JUNGLE_LOGS.item();
      CHERRY_LOGS = BlockItemTags.CHERRY_LOGS.item();
      CRIMSON_STEMS = BlockItemTags.CRIMSON_STEMS.item();
      WARPED_STEMS = BlockItemTags.WARPED_STEMS.item();
      WART_BLOCKS = BlockItemTags.WART_BLOCKS.item();
      LOGS_THAT_BURN = BlockItemTags.LOGS_THAT_BURN.item();
      LOGS = BlockItemTags.LOGS.item();
      SAND = BlockItemTags.SAND.item();
      SMELTS_TO_GLASS = BlockItemTags.SMELTS_TO_GLASS.item();
      WALLS = BlockItemTags.WALLS.item();
      ANVIL = BlockItemTags.ANVIL.item();
      RAILS = BlockItemTags.RAILS.item();
      LEAVES = BlockItemTags.LEAVES.item();
      WOODEN_TRAPDOORS = BlockItemTags.WOODEN_TRAPDOORS.item();
      BEDS = BlockItemTags.BEDS.item();
      SOUL_FIRE_BASE_BLOCKS = BlockItemTags.SOUL_FIRE_BASE_BLOCKS.item();
      CANDLES = BlockItemTags.CANDLES.item();
      DAMPENS_VIBRATIONS = BlockItemTags.DAMPENS_VIBRATIONS.item();
      GOLD_ORES = BlockItemTags.GOLD_ORES.item();
      IRON_ORES = BlockItemTags.IRON_ORES.item();
      DIAMOND_ORES = BlockItemTags.DIAMOND_ORES.item();
      REDSTONE_ORES = BlockItemTags.REDSTONE_ORES.item();
      LAPIS_ORES = BlockItemTags.LAPIS_ORES.item();
      COAL_ORES = BlockItemTags.COAL_ORES.item();
      EMERALD_ORES = BlockItemTags.EMERALD_ORES.item();
      COPPER_ORES = BlockItemTags.COPPER_ORES.item();
      DIRT = BlockItemTags.DIRT.item();
      MUD = BlockItemTags.MUD.item();
      MOSS_BLOCKS = BlockItemTags.MOSS_BLOCKS.item();
      TERRACOTTA = BlockItemTags.TERRACOTTA.item();
      GLAZED_TERRACOTTA = BlockItemTags.GLAZED_TERRACOTTA.item();
      CONCRETE = BlockItemTags.CONCRETE.item();
      CONCRETE_POWDERS = BlockItemTags.CONCRETE_POWDERS.item();
      COMPLETES_FIND_TREE_TUTORIAL = BlockItemTags.COMPLETES_FIND_TREE_TUTORIAL.item();
      SHULKER_BOXES = BlockItemTags.SHULKER_BOXES.item();
      COPPER = BlockItemTags.COPPER.item();
      SIGNS = BlockItemTags.SIGNS.item();
      HANGING_SIGNS = BlockItemTags.HANGING_SIGNS.item();
      BEE_FOOD = BlockItemTags.BEE_FOOD.item();
      SULFUR_CUBE_ARCHETYPE_BOUNCY = bind("sulfur_cube_archetype/bouncy");
      SULFUR_CUBE_ARCHETYPE_REGULAR = bind("sulfur_cube_archetype/regular");
      SULFUR_CUBE_ARCHETYPE_SLOW_FLAT = bind("sulfur_cube_archetype/slow_flat");
      SULFUR_CUBE_ARCHETYPE_FAST_FLAT = bind("sulfur_cube_archetype/fast_flat");
      SULFUR_CUBE_ARCHETYPE_LIGHT = bind("sulfur_cube_archetype/light");
      SULFUR_CUBE_ARCHETYPE_FAST_SLIDING = bind("sulfur_cube_archetype/fast_sliding");
      SULFUR_CUBE_ARCHETYPE_SLOW_SLIDING = bind("sulfur_cube_archetype/slow_sliding");
      SULFUR_CUBE_ARCHETYPE_STICKY = bind("sulfur_cube_archetype/sticky");
      SULFUR_CUBE_ARCHETYPE_HIGH_RESISTANCE = bind("sulfur_cube_archetype/high_resistance");
      SULFUR_CUBE_ARCHETYPE_EXPLOSIVE = bind("sulfur_cube_archetype/explosive");
      SULFUR_CUBE_SWALLOWABLE = bind("sulfur_cube_swallowable");
      BANNERS = bind("banners");
      PIGLIN_REPELLENTS = bind("piglin_repellents");
      PIGLIN_LOVED = bind("piglin_loved");
      IGNORED_BY_PIGLIN_BABIES = bind("ignored_by_piglin_babies");
      PIGLIN_SAFE_ARMOR = bind("piglin_safe_armor");
      DUPLICATES_ALLAYS = bind("duplicates_allays");
      BREWING_FUEL = bind("brewing_fuel");
      EGGS = bind("eggs");
      MEAT = bind("meat");
      SNIFFER_FOOD = bind("sniffer_food");
      PIGLIN_FOOD = bind("piglin_food");
      FOX_FOOD = bind("fox_food");
      COW_FOOD = bind("cow_food");
      GOAT_FOOD = bind("goat_food");
      SHEEP_FOOD = bind("sheep_food");
      WOLF_FOOD = bind("wolf_food");
      CAT_FOOD = bind("cat_food");
      HORSE_FOOD = bind("horse_food");
      ZOMBIE_HORSE_FOOD = bind("zombie_horse_food");
      HORSE_TEMPT_ITEMS = bind("horse_tempt_items");
      HARNESSES = bind("harnesses");
      HAPPY_GHAST_FOOD = bind("happy_ghast_food");
      HAPPY_GHAST_TEMPT_ITEMS = bind("happy_ghast_tempt_items");
      CAMEL_FOOD = bind("camel_food");
      CAMEL_HUSK_FOOD = bind("camel_husk_food");
      ARMADILLO_FOOD = bind("armadillo_food");
      CHICKEN_FOOD = bind("chicken_food");
      FROG_FOOD = bind("frog_food");
      HOGLIN_FOOD = bind("hoglin_food");
      LLAMA_FOOD = bind("llama_food");
      LLAMA_TEMPT_ITEMS = bind("llama_tempt_items");
      OCELOT_FOOD = bind("ocelot_food");
      PANDA_FOOD = bind("panda_food");
      PANDA_EATS_FROM_GROUND = bind("panda_eats_from_ground");
      PIG_FOOD = bind("pig_food");
      RABBIT_FOOD = bind("rabbit_food");
      STRIDER_FOOD = bind("strider_food");
      STRIDER_TEMPT_ITEMS = bind("strider_tempt_items");
      TURTLE_FOOD = bind("turtle_food");
      PARROT_FOOD = bind("parrot_food");
      PARROT_POISONOUS_FOOD = bind("parrot_poisonous_food");
      AXOLOTL_FOOD = bind("axolotl_food");
      NAUTILUS_BUCKET_FOOD = bind("nautilus_bucket_food");
      NAUTILUS_FOOD = bind("nautilus_food");
      NAUTILUS_TAMING_ITEMS = bind("nautilus_taming_items");
      SULFUR_CUBE_FOOD = bind("sulfur_cube_food");
      NON_FLAMMABLE_WOOD = bind("non_flammable_wood");
      BOATS = bind("boats");
      CHEST_BOATS = bind("chest_boats");
      FISHES = bind("fishes");
      CREEPER_DROP_MUSIC_DISCS = bind("creeper_drop_music_discs");
      COALS = bind("coals");
      ARROWS = bind("arrows");
      LECTERN_BOOKS = bind("lectern_books");
      BOOKSHELF_BOOKS = bind("bookshelf_books");
      BEACON_PAYMENT_ITEMS = bind("beacon_payment_items");
      WOODEN_TOOL_MATERIALS = bind("wooden_tool_materials");
      STONE_TOOL_MATERIALS = bind("stone_tool_materials");
      COPPER_TOOL_MATERIALS = bind("copper_tool_materials");
      IRON_TOOL_MATERIALS = bind("iron_tool_materials");
      GOLD_TOOL_MATERIALS = bind("gold_tool_materials");
      DIAMOND_TOOL_MATERIALS = bind("diamond_tool_materials");
      NETHERITE_TOOL_MATERIALS = bind("netherite_tool_materials");
      REPAIRS_LEATHER_ARMOR = bind("repairs_leather_armor");
      REPAIRS_COPPER_ARMOR = bind("repairs_copper_armor");
      REPAIRS_CHAIN_ARMOR = bind("repairs_chain_armor");
      REPAIRS_IRON_ARMOR = bind("repairs_iron_armor");
      REPAIRS_GOLD_ARMOR = bind("repairs_gold_armor");
      REPAIRS_DIAMOND_ARMOR = bind("repairs_diamond_armor");
      REPAIRS_NETHERITE_ARMOR = bind("repairs_netherite_armor");
      REPAIRS_TURTLE_HELMET = bind("repairs_turtle_helmet");
      REPAIRS_WOLF_ARMOR = bind("repairs_wolf_armor");
      STONE_CRAFTING_MATERIALS = bind("stone_crafting_materials");
      FREEZE_IMMUNE_WEARABLES = bind("freeze_immune_wearables");
      CLUSTER_MAX_HARVESTABLES = bind("cluster_max_harvestables");
      COMPASSES = bind("compasses");
      CREEPER_IGNITERS = bind("creeper_igniters");
      NOTE_BLOCK_TOP_INSTRUMENTS = bind("noteblock_top_instruments");
      FOOT_ARMOR = bind("foot_armor");
      LEG_ARMOR = bind("leg_armor");
      CHEST_ARMOR = bind("chest_armor");
      HEAD_ARMOR = bind("head_armor");
      SKULLS = bind("skulls");
      TRIMMABLE_ARMOR = bind("trimmable_armor");
      TRIM_MATERIALS = bind("trim_materials");
      DECORATED_POT_SHERDS = bind("decorated_pot_sherds");
      DECORATED_POT_INGREDIENTS = bind("decorated_pot_ingredients");
      SWORDS = bind("swords");
      AXES = bind("axes");
      HOES = bind("hoes");
      PICKAXES = bind("pickaxes");
      SHOVELS = bind("shovels");
      SPEARS = bind("spears");
      BREAKS_DECORATED_POTS = bind("breaks_decorated_pots");
      VILLAGER_PLANTABLE_SEEDS = bind("villager_plantable_seeds");
      VILLAGER_PICKS_UP = bind("villager_picks_up");
      FURNACE_MINECART_FUEL = bind("furnace_minecart_fuel");
      BUNDLES = bind("bundles");
      BOOK_CLONING_TARGET = bind("book_cloning_target");
      DYES = bind("dyes");
      LOOM_DYES = bind("loom_dyes");
      LOOM_PATTERNS = bind("loom_patterns");
      CAULDRON_CAN_REMOVE_DYE = bind("cauldron_can_remove_dye");
      CAT_COLLAR_DYES = bind("cat_collar_dyes");
      WOLF_COLLAR_DYES = bind("wolf_collar_dyes");
      SKELETON_PREFERRED_WEAPONS = bind("skeleton_preferred_weapons");
      DROWNED_PREFERRED_WEAPONS = bind("drowned_preferred_weapons");
      PIGLIN_PREFERRED_WEAPONS = bind("piglin_preferred_weapons");
      PILLAGER_PREFERRED_WEAPONS = bind("pillager_preferred_weapons");
      WITHER_SKELETON_DISLIKED_WEAPONS = bind("wither_skeleton_disliked_weapons");
      SHEARABLE_FROM_COPPER_GOLEM = bind("shearable_from_copper_golem");
      METAL_NUGGETS = bind("metal_nuggets");
      FOOT_ARMOR_ENCHANTABLE = bind("enchantable/foot_armor");
      LEG_ARMOR_ENCHANTABLE = bind("enchantable/leg_armor");
      CHEST_ARMOR_ENCHANTABLE = bind("enchantable/chest_armor");
      HEAD_ARMOR_ENCHANTABLE = bind("enchantable/head_armor");
      ARMOR_ENCHANTABLE = bind("enchantable/armor");
      MELEE_WEAPON_ENCHANTABLE = bind("enchantable/melee_weapon");
      SWEEPING_ENCHANTABLE = bind("enchantable/sweeping");
      FIRE_ASPECT_ENCHANTABLE = bind("enchantable/fire_aspect");
      SHARP_WEAPON_ENCHANTABLE = bind("enchantable/sharp_weapon");
      WEAPON_ENCHANTABLE = bind("enchantable/weapon");
      MINING_ENCHANTABLE = bind("enchantable/mining");
      MINING_LOOT_ENCHANTABLE = bind("enchantable/mining_loot");
      FISHING_ENCHANTABLE = bind("enchantable/fishing");
      TRIDENT_ENCHANTABLE = bind("enchantable/trident");
      LUNGE_ENCHANTABLE = bind("enchantable/lunge");
      DURABILITY_ENCHANTABLE = bind("enchantable/durability");
      BOW_ENCHANTABLE = bind("enchantable/bow");
      EQUIPPABLE_ENCHANTABLE = bind("enchantable/equippable");
      CROSSBOW_ENCHANTABLE = bind("enchantable/crossbow");
      VANISHING_ENCHANTABLE = bind("enchantable/vanishing");
      MACE_ENCHANTABLE = bind("enchantable/mace");
      MAP_INVISIBILITY_EQUIPMENT = bind("map_invisibility_equipment");
      GAZE_DISGUISE_EQUIPMENT = bind("gaze_disguise_equipment");
   }
}
