package net.minecraft.references;

import java.util.function.UnaryOperator;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EntityTypeIds;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.JukeboxSong;
import net.minecraft.world.item.JukeboxSongs;
import net.minecraft.world.item.equipment.trim.TrimPattern;
import net.minecraft.world.item.equipment.trim.TrimPatterns;
import net.minecraft.world.level.block.ColorCollection;
import net.minecraft.world.level.block.entity.DecoratedPotPattern;
import net.minecraft.world.level.block.entity.DecoratedPotPatterns;

public class ItemIds {
   public static final ResourceKey<Item> SADDLE = create("saddle");
   public static final ResourceKey<Item> MINECART = create("minecart");
   public static final ResourceKey<Item> CHEST_MINECART = create("chest_minecart");
   public static final ResourceKey<Item> FURNACE_MINECART = create("furnace_minecart");
   public static final ResourceKey<Item> TNT_MINECART = create("tnt_minecart");
   public static final ResourceKey<Item> HOPPER_MINECART = create("hopper_minecart");
   public static final ResourceKey<Item> CARROT_ON_A_STICK = create("carrot_on_a_stick");
   public static final ResourceKey<Item> WARPED_FUNGUS_ON_A_STICK = create("warped_fungus_on_a_stick");
   public static final ResourceKey<Item> PHANTOM_MEMBRANE = create("phantom_membrane");
   public static final ResourceKey<Item> ELYTRA = create("elytra");
   public static final ResourceKey<Item> OAK_BOAT = create("oak_boat");
   public static final ResourceKey<Item> OAK_CHEST_BOAT = create("oak_chest_boat");
   public static final ResourceKey<Item> SPRUCE_BOAT = create("spruce_boat");
   public static final ResourceKey<Item> SPRUCE_CHEST_BOAT = create("spruce_chest_boat");
   public static final ResourceKey<Item> BIRCH_BOAT = create("birch_boat");
   public static final ResourceKey<Item> BIRCH_CHEST_BOAT = create("birch_chest_boat");
   public static final ResourceKey<Item> JUNGLE_BOAT = create("jungle_boat");
   public static final ResourceKey<Item> JUNGLE_CHEST_BOAT = create("jungle_chest_boat");
   public static final ResourceKey<Item> ACACIA_BOAT = create("acacia_boat");
   public static final ResourceKey<Item> ACACIA_CHEST_BOAT = create("acacia_chest_boat");
   public static final ResourceKey<Item> CHERRY_BOAT = create("cherry_boat");
   public static final ResourceKey<Item> CHERRY_CHEST_BOAT = create("cherry_chest_boat");
   public static final ResourceKey<Item> DARK_OAK_BOAT = create("dark_oak_boat");
   public static final ResourceKey<Item> DARK_OAK_CHEST_BOAT = create("dark_oak_chest_boat");
   public static final ResourceKey<Item> PALE_OAK_BOAT = create("pale_oak_boat");
   public static final ResourceKey<Item> PALE_OAK_CHEST_BOAT = create("pale_oak_chest_boat");
   public static final ResourceKey<Item> MANGROVE_BOAT = create("mangrove_boat");
   public static final ResourceKey<Item> MANGROVE_CHEST_BOAT = create("mangrove_chest_boat");
   public static final ResourceKey<Item> BAMBOO_RAFT = create("bamboo_raft");
   public static final ResourceKey<Item> BAMBOO_CHEST_RAFT = create("bamboo_chest_raft");
   public static final ResourceKey<Item> TURTLE_HELMET = create("turtle_helmet");
   public static final ResourceKey<Item> TURTLE_SCUTE = create("turtle_scute");
   public static final ResourceKey<Item> ARMADILLO_SCUTE = create("armadillo_scute");
   public static final ResourceKey<Item> WOLF_ARMOR = create("wolf_armor");
   public static final ResourceKey<Item> FLINT_AND_STEEL = create("flint_and_steel");
   public static final ResourceKey<Item> BOWL = create("bowl");
   public static final ResourceKey<Item> APPLE = create("apple");
   public static final ResourceKey<Item> BOW = create("bow");
   public static final ResourceKey<Item> ARROW = create("arrow");
   public static final ResourceKey<Item> COAL = create("coal");
   public static final ResourceKey<Item> CHARCOAL = create("charcoal");
   public static final ResourceKey<Item> DIAMOND = create("diamond");
   public static final ResourceKey<Item> EMERALD = create("emerald");
   public static final ResourceKey<Item> LAPIS_LAZULI = create("lapis_lazuli");
   public static final ResourceKey<Item> QUARTZ = create("quartz");
   public static final ResourceKey<Item> AMETHYST_SHARD = create("amethyst_shard");
   public static final ResourceKey<Item> RAW_IRON = create("raw_iron");
   public static final ResourceKey<Item> IRON_INGOT = create("iron_ingot");
   public static final ResourceKey<Item> RAW_COPPER = create("raw_copper");
   public static final ResourceKey<Item> COPPER_INGOT = create("copper_ingot");
   public static final ResourceKey<Item> RAW_GOLD = create("raw_gold");
   public static final ResourceKey<Item> GOLD_INGOT = create("gold_ingot");
   public static final ResourceKey<Item> NETHERITE_INGOT = create("netherite_ingot");
   public static final ResourceKey<Item> NETHERITE_SCRAP = create("netherite_scrap");
   public static final ResourceKey<Item> WOODEN_SWORD = create("wooden_sword");
   public static final ResourceKey<Item> WOODEN_SHOVEL = create("wooden_shovel");
   public static final ResourceKey<Item> WOODEN_PICKAXE = create("wooden_pickaxe");
   public static final ResourceKey<Item> WOODEN_AXE = create("wooden_axe");
   public static final ResourceKey<Item> WOODEN_HOE = create("wooden_hoe");
   public static final ResourceKey<Item> COPPER_SWORD = create("copper_sword");
   public static final ResourceKey<Item> COPPER_SHOVEL = create("copper_shovel");
   public static final ResourceKey<Item> COPPER_PICKAXE = create("copper_pickaxe");
   public static final ResourceKey<Item> COPPER_AXE = create("copper_axe");
   public static final ResourceKey<Item> COPPER_HOE = create("copper_hoe");
   public static final ResourceKey<Item> STONE_SWORD = create("stone_sword");
   public static final ResourceKey<Item> STONE_SHOVEL = create("stone_shovel");
   public static final ResourceKey<Item> STONE_PICKAXE = create("stone_pickaxe");
   public static final ResourceKey<Item> STONE_AXE = create("stone_axe");
   public static final ResourceKey<Item> STONE_HOE = create("stone_hoe");
   public static final ResourceKey<Item> GOLDEN_SWORD = create("golden_sword");
   public static final ResourceKey<Item> GOLDEN_SHOVEL = create("golden_shovel");
   public static final ResourceKey<Item> GOLDEN_PICKAXE = create("golden_pickaxe");
   public static final ResourceKey<Item> GOLDEN_AXE = create("golden_axe");
   public static final ResourceKey<Item> GOLDEN_HOE = create("golden_hoe");
   public static final ResourceKey<Item> IRON_SWORD = create("iron_sword");
   public static final ResourceKey<Item> IRON_SHOVEL = create("iron_shovel");
   public static final ResourceKey<Item> IRON_PICKAXE = create("iron_pickaxe");
   public static final ResourceKey<Item> IRON_AXE = create("iron_axe");
   public static final ResourceKey<Item> IRON_HOE = create("iron_hoe");
   public static final ResourceKey<Item> DIAMOND_SWORD = create("diamond_sword");
   public static final ResourceKey<Item> DIAMOND_SHOVEL = create("diamond_shovel");
   public static final ResourceKey<Item> DIAMOND_PICKAXE = create("diamond_pickaxe");
   public static final ResourceKey<Item> DIAMOND_AXE = create("diamond_axe");
   public static final ResourceKey<Item> DIAMOND_HOE = create("diamond_hoe");
   public static final ResourceKey<Item> NETHERITE_SWORD = create("netherite_sword");
   public static final ResourceKey<Item> NETHERITE_SHOVEL = create("netherite_shovel");
   public static final ResourceKey<Item> NETHERITE_PICKAXE = create("netherite_pickaxe");
   public static final ResourceKey<Item> NETHERITE_AXE = create("netherite_axe");
   public static final ResourceKey<Item> NETHERITE_HOE = create("netherite_hoe");
   public static final ResourceKey<Item> STICK = create("stick");
   public static final ResourceKey<Item> MUSHROOM_STEW = create("mushroom_stew");
   public static final ResourceKey<Item> FEATHER = create("feather");
   public static final ResourceKey<Item> GUNPOWDER = create("gunpowder");
   public static final ResourceKey<Item> WHEAT = create("wheat");
   public static final ResourceKey<Item> BREAD = create("bread");
   public static final ResourceKey<Item> LEATHER_HELMET = create("leather_helmet");
   public static final ResourceKey<Item> LEATHER_CHESTPLATE = create("leather_chestplate");
   public static final ResourceKey<Item> LEATHER_LEGGINGS = create("leather_leggings");
   public static final ResourceKey<Item> LEATHER_BOOTS = create("leather_boots");
   public static final ResourceKey<Item> COPPER_HELMET = create("copper_helmet");
   public static final ResourceKey<Item> COPPER_CHESTPLATE = create("copper_chestplate");
   public static final ResourceKey<Item> COPPER_LEGGINGS = create("copper_leggings");
   public static final ResourceKey<Item> COPPER_BOOTS = create("copper_boots");
   public static final ResourceKey<Item> CHAINMAIL_HELMET = create("chainmail_helmet");
   public static final ResourceKey<Item> CHAINMAIL_CHESTPLATE = create("chainmail_chestplate");
   public static final ResourceKey<Item> CHAINMAIL_LEGGINGS = create("chainmail_leggings");
   public static final ResourceKey<Item> CHAINMAIL_BOOTS = create("chainmail_boots");
   public static final ResourceKey<Item> IRON_HELMET = create("iron_helmet");
   public static final ResourceKey<Item> IRON_CHESTPLATE = create("iron_chestplate");
   public static final ResourceKey<Item> IRON_LEGGINGS = create("iron_leggings");
   public static final ResourceKey<Item> IRON_BOOTS = create("iron_boots");
   public static final ResourceKey<Item> DIAMOND_HELMET = create("diamond_helmet");
   public static final ResourceKey<Item> DIAMOND_CHESTPLATE = create("diamond_chestplate");
   public static final ResourceKey<Item> DIAMOND_LEGGINGS = create("diamond_leggings");
   public static final ResourceKey<Item> DIAMOND_BOOTS = create("diamond_boots");
   public static final ResourceKey<Item> GOLDEN_HELMET = create("golden_helmet");
   public static final ResourceKey<Item> GOLDEN_CHESTPLATE = create("golden_chestplate");
   public static final ResourceKey<Item> GOLDEN_LEGGINGS = create("golden_leggings");
   public static final ResourceKey<Item> GOLDEN_BOOTS = create("golden_boots");
   public static final ResourceKey<Item> NETHERITE_HELMET = create("netherite_helmet");
   public static final ResourceKey<Item> NETHERITE_CHESTPLATE = create("netherite_chestplate");
   public static final ResourceKey<Item> NETHERITE_LEGGINGS = create("netherite_leggings");
   public static final ResourceKey<Item> NETHERITE_BOOTS = create("netherite_boots");
   public static final ResourceKey<Item> FLINT = create("flint");
   public static final ResourceKey<Item> PORKCHOP = create("porkchop");
   public static final ResourceKey<Item> COOKED_PORKCHOP = create("cooked_porkchop");
   public static final ResourceKey<Item> PAINTING = create("painting");
   public static final ResourceKey<Item> GOLDEN_APPLE = create("golden_apple");
   public static final ResourceKey<Item> ENCHANTED_GOLDEN_APPLE = create("enchanted_golden_apple");
   public static final ResourceKey<Item> BUCKET = create("bucket");
   public static final ResourceKey<Item> WATER_BUCKET = create("water_bucket");
   public static final ResourceKey<Item> LAVA_BUCKET = create("lava_bucket");
   public static final ResourceKey<Item> SNOWBALL = create("snowball");
   public static final ResourceKey<Item> LEATHER = create("leather");
   public static final ResourceKey<Item> MILK_BUCKET = create("milk_bucket");
   public static final ResourceKey<Item> PUFFERFISH_BUCKET = create("pufferfish_bucket");
   public static final ResourceKey<Item> SALMON_BUCKET = create("salmon_bucket");
   public static final ResourceKey<Item> COD_BUCKET = create("cod_bucket");
   public static final ResourceKey<Item> TROPICAL_FISH_BUCKET = create("tropical_fish_bucket");
   public static final ResourceKey<Item> AXOLOTL_BUCKET = create("axolotl_bucket");
   public static final ResourceKey<Item> SULFUR_CUBE_BUCKET = create("sulfur_cube_bucket");
   public static final ResourceKey<Item> TADPOLE_BUCKET = create("tadpole_bucket");
   public static final ResourceKey<Item> BRICK = create("brick");
   public static final ResourceKey<Item> CLAY_BALL = create("clay_ball");
   public static final ResourceKey<Item> PAPER = create("paper");
   public static final ResourceKey<Item> BOOK = create("book");
   public static final ResourceKey<Item> SLIME_BALL = create("slime_ball");
   public static final ResourceKey<Item> EGG = create("egg");
   public static final ResourceKey<Item> BLUE_EGG = create("blue_egg");
   public static final ResourceKey<Item> BROWN_EGG = create("brown_egg");
   public static final ResourceKey<Item> COMPASS = create("compass");
   public static final ResourceKey<Item> RECOVERY_COMPASS = create("recovery_compass");
   public static final ResourceKey<Item> BUNDLE = create("bundle");
   public static final ResourceKey<Item> FISHING_ROD = create("fishing_rod");
   public static final ResourceKey<Item> CLOCK = create("clock");
   public static final ResourceKey<Item> SPYGLASS = create("spyglass");
   public static final ResourceKey<Item> GLOWSTONE_DUST = create("glowstone_dust");
   public static final ResourceKey<Item> COD = create("cod");
   public static final ResourceKey<Item> SALMON = create("salmon");
   public static final ResourceKey<Item> TROPICAL_FISH = create("tropical_fish");
   public static final ResourceKey<Item> PUFFERFISH = create("pufferfish");
   public static final ResourceKey<Item> COOKED_COD = create("cooked_cod");
   public static final ResourceKey<Item> COOKED_SALMON = create("cooked_salmon");
   public static final ResourceKey<Item> INK_SAC = create("ink_sac");
   public static final ResourceKey<Item> GLOW_INK_SAC = create("glow_ink_sac");
   public static final ResourceKey<Item> BONE_MEAL = create("bone_meal");
   public static final ResourceKey<Item> BONE = create("bone");
   public static final ResourceKey<Item> SUGAR = create("sugar");
   public static final ResourceKey<Item> COOKIE = create("cookie");
   public static final ResourceKey<Item> FILLED_MAP = create("filled_map");
   public static final ResourceKey<Item> SHEARS = create("shears");
   public static final ResourceKey<Item> MELON_SLICE = create("melon_slice");
   public static final ResourceKey<Item> DRIED_KELP = create("dried_kelp");
   public static final ResourceKey<Item> BEEF = create("beef");
   public static final ResourceKey<Item> COOKED_BEEF = create("cooked_beef");
   public static final ResourceKey<Item> CHICKEN = create("chicken");
   public static final ResourceKey<Item> COOKED_CHICKEN = create("cooked_chicken");
   public static final ResourceKey<Item> ROTTEN_FLESH = create("rotten_flesh");
   public static final ResourceKey<Item> ENDER_PEARL = create("ender_pearl");
   public static final ResourceKey<Item> BLAZE_ROD = create("blaze_rod");
   public static final ResourceKey<Item> GHAST_TEAR = create("ghast_tear");
   public static final ResourceKey<Item> GOLD_NUGGET = create("gold_nugget");
   public static final ResourceKey<Item> GLASS_BOTTLE = create("glass_bottle");
   public static final ResourceKey<Item> POTION = create("potion");
   public static final ResourceKey<Item> SPIDER_EYE = create("spider_eye");
   public static final ResourceKey<Item> FERMENTED_SPIDER_EYE = create("fermented_spider_eye");
   public static final ResourceKey<Item> BLAZE_POWDER = create("blaze_powder");
   public static final ResourceKey<Item> MAGMA_CREAM = create("magma_cream");
   public static final ResourceKey<Item> ENDER_EYE = create("ender_eye");
   public static final ResourceKey<Item> GLISTERING_MELON_SLICE = create("glistering_melon_slice");
   public static final ResourceKey<Item> CHICKEN_SPAWN_EGG;
   public static final ResourceKey<Item> COW_SPAWN_EGG;
   public static final ResourceKey<Item> PIG_SPAWN_EGG;
   public static final ResourceKey<Item> SHEEP_SPAWN_EGG;
   public static final ResourceKey<Item> CAMEL_SPAWN_EGG;
   public static final ResourceKey<Item> DONKEY_SPAWN_EGG;
   public static final ResourceKey<Item> HORSE_SPAWN_EGG;
   public static final ResourceKey<Item> MULE_SPAWN_EGG;
   public static final ResourceKey<Item> CAT_SPAWN_EGG;
   public static final ResourceKey<Item> PARROT_SPAWN_EGG;
   public static final ResourceKey<Item> WOLF_SPAWN_EGG;
   public static final ResourceKey<Item> ARMADILLO_SPAWN_EGG;
   public static final ResourceKey<Item> BAT_SPAWN_EGG;
   public static final ResourceKey<Item> BEE_SPAWN_EGG;
   public static final ResourceKey<Item> FOX_SPAWN_EGG;
   public static final ResourceKey<Item> GOAT_SPAWN_EGG;
   public static final ResourceKey<Item> LLAMA_SPAWN_EGG;
   public static final ResourceKey<Item> OCELOT_SPAWN_EGG;
   public static final ResourceKey<Item> PANDA_SPAWN_EGG;
   public static final ResourceKey<Item> POLAR_BEAR_SPAWN_EGG;
   public static final ResourceKey<Item> RABBIT_SPAWN_EGG;
   public static final ResourceKey<Item> AXOLOTL_SPAWN_EGG;
   public static final ResourceKey<Item> COD_SPAWN_EGG;
   public static final ResourceKey<Item> DOLPHIN_SPAWN_EGG;
   public static final ResourceKey<Item> FROG_SPAWN_EGG;
   public static final ResourceKey<Item> GLOW_SQUID_SPAWN_EGG;
   public static final ResourceKey<Item> NAUTILUS_SPAWN_EGG;
   public static final ResourceKey<Item> PUFFERFISH_SPAWN_EGG;
   public static final ResourceKey<Item> SALMON_SPAWN_EGG;
   public static final ResourceKey<Item> SQUID_SPAWN_EGG;
   public static final ResourceKey<Item> TADPOLE_SPAWN_EGG;
   public static final ResourceKey<Item> TROPICAL_FISH_SPAWN_EGG;
   public static final ResourceKey<Item> TURTLE_SPAWN_EGG;
   public static final ResourceKey<Item> ALLAY_SPAWN_EGG;
   public static final ResourceKey<Item> MOOSHROOM_SPAWN_EGG;
   public static final ResourceKey<Item> SNIFFER_SPAWN_EGG;
   public static final ResourceKey<Item> SULFUR_CUBE_SPAWN_EGG;
   public static final ResourceKey<Item> COPPER_GOLEM_SPAWN_EGG;
   public static final ResourceKey<Item> IRON_GOLEM_SPAWN_EGG;
   public static final ResourceKey<Item> SNOW_GOLEM_SPAWN_EGG;
   public static final ResourceKey<Item> TRADER_LLAMA_SPAWN_EGG;
   public static final ResourceKey<Item> VILLAGER_SPAWN_EGG;
   public static final ResourceKey<Item> WANDERING_TRADER_SPAWN_EGG;
   public static final ResourceKey<Item> BOGGED_SPAWN_EGG;
   public static final ResourceKey<Item> CAMEL_HUSK_SPAWN_EGG;
   public static final ResourceKey<Item> DROWNED_SPAWN_EGG;
   public static final ResourceKey<Item> HUSK_SPAWN_EGG;
   public static final ResourceKey<Item> PARCHED_SPAWN_EGG;
   public static final ResourceKey<Item> SKELETON_SPAWN_EGG;
   public static final ResourceKey<Item> SKELETON_HORSE_SPAWN_EGG;
   public static final ResourceKey<Item> STRAY_SPAWN_EGG;
   public static final ResourceKey<Item> WITHER_SPAWN_EGG;
   public static final ResourceKey<Item> WITHER_SKELETON_SPAWN_EGG;
   public static final ResourceKey<Item> ZOMBIE_SPAWN_EGG;
   public static final ResourceKey<Item> ZOMBIE_HORSE_SPAWN_EGG;
   public static final ResourceKey<Item> ZOMBIE_NAUTILUS_SPAWN_EGG;
   public static final ResourceKey<Item> ZOMBIE_VILLAGER_SPAWN_EGG;
   public static final ResourceKey<Item> CAVE_SPIDER_SPAWN_EGG;
   public static final ResourceKey<Item> SPIDER_SPAWN_EGG;
   public static final ResourceKey<Item> BREEZE_SPAWN_EGG;
   public static final ResourceKey<Item> CREAKING_SPAWN_EGG;
   public static final ResourceKey<Item> CREEPER_SPAWN_EGG;
   public static final ResourceKey<Item> ELDER_GUARDIAN_SPAWN_EGG;
   public static final ResourceKey<Item> GUARDIAN_SPAWN_EGG;
   public static final ResourceKey<Item> PHANTOM_SPAWN_EGG;
   public static final ResourceKey<Item> SILVERFISH_SPAWN_EGG;
   public static final ResourceKey<Item> SLIME_SPAWN_EGG;
   public static final ResourceKey<Item> WARDEN_SPAWN_EGG;
   public static final ResourceKey<Item> WITCH_SPAWN_EGG;
   public static final ResourceKey<Item> EVOKER_SPAWN_EGG;
   public static final ResourceKey<Item> PILLAGER_SPAWN_EGG;
   public static final ResourceKey<Item> RAVAGER_SPAWN_EGG;
   public static final ResourceKey<Item> VINDICATOR_SPAWN_EGG;
   public static final ResourceKey<Item> VEX_SPAWN_EGG;
   public static final ResourceKey<Item> BLAZE_SPAWN_EGG;
   public static final ResourceKey<Item> GHAST_SPAWN_EGG;
   public static final ResourceKey<Item> HAPPY_GHAST_SPAWN_EGG;
   public static final ResourceKey<Item> HOGLIN_SPAWN_EGG;
   public static final ResourceKey<Item> MAGMA_CUBE_SPAWN_EGG;
   public static final ResourceKey<Item> PIGLIN_SPAWN_EGG;
   public static final ResourceKey<Item> PIGLIN_BRUTE_SPAWN_EGG;
   public static final ResourceKey<Item> STRIDER_SPAWN_EGG;
   public static final ResourceKey<Item> ZOGLIN_SPAWN_EGG;
   public static final ResourceKey<Item> ZOMBIFIED_PIGLIN_SPAWN_EGG;
   public static final ResourceKey<Item> ENDER_DRAGON_SPAWN_EGG;
   public static final ResourceKey<Item> ENDERMAN_SPAWN_EGG;
   public static final ResourceKey<Item> ENDERMITE_SPAWN_EGG;
   public static final ResourceKey<Item> SHULKER_SPAWN_EGG;
   public static final ResourceKey<Item> EXPERIENCE_BOTTLE;
   public static final ResourceKey<Item> FIRE_CHARGE;
   public static final ResourceKey<Item> WIND_CHARGE;
   public static final ResourceKey<Item> WRITABLE_BOOK;
   public static final ResourceKey<Item> WRITTEN_BOOK;
   public static final ResourceKey<Item> BREEZE_ROD;
   public static final ResourceKey<Item> MACE;
   public static final ResourceKey<Item> ITEM_FRAME;
   public static final ResourceKey<Item> GLOW_ITEM_FRAME;
   public static final ResourceKey<Item> BAKED_POTATO;
   public static final ResourceKey<Item> POISONOUS_POTATO;
   public static final ResourceKey<Item> MAP;
   public static final ResourceKey<Item> GOLDEN_CARROT;
   public static final ResourceKey<Item> NETHER_STAR;
   public static final ResourceKey<Item> PUMPKIN_PIE;
   public static final ResourceKey<Item> FIREWORK_ROCKET;
   public static final ResourceKey<Item> FIREWORK_STAR;
   public static final ResourceKey<Item> ENCHANTED_BOOK;
   public static final ResourceKey<Item> NETHER_BRICK;
   public static final ResourceKey<Item> RESIN_BRICK;
   public static final ResourceKey<Item> PRISMARINE_SHARD;
   public static final ResourceKey<Item> PRISMARINE_CRYSTALS;
   public static final ResourceKey<Item> RABBIT;
   public static final ResourceKey<Item> COOKED_RABBIT;
   public static final ResourceKey<Item> RABBIT_STEW;
   public static final ResourceKey<Item> RABBIT_FOOT;
   public static final ResourceKey<Item> RABBIT_HIDE;
   public static final ResourceKey<Item> ARMOR_STAND;
   public static final ResourceKey<Item> COPPER_HORSE_ARMOR;
   public static final ResourceKey<Item> IRON_HORSE_ARMOR;
   public static final ResourceKey<Item> GOLDEN_HORSE_ARMOR;
   public static final ResourceKey<Item> DIAMOND_HORSE_ARMOR;
   public static final ResourceKey<Item> NETHERITE_HORSE_ARMOR;
   public static final ResourceKey<Item> LEATHER_HORSE_ARMOR;
   public static final ResourceKey<Item> LEAD;
   public static final ResourceKey<Item> NAME_TAG;
   public static final ResourceKey<Item> COMMAND_BLOCK_MINECART;
   public static final ResourceKey<Item> MUTTON;
   public static final ResourceKey<Item> COOKED_MUTTON;
   public static final ResourceKey<Item> END_CRYSTAL;
   public static final ResourceKey<Item> CHORUS_FRUIT;
   public static final ResourceKey<Item> POPPED_CHORUS_FRUIT;
   public static final ResourceKey<Item> BEETROOT;
   public static final ResourceKey<Item> BEETROOT_SOUP;
   public static final ResourceKey<Item> DRAGON_BREATH;
   public static final ResourceKey<Item> SPLASH_POTION;
   public static final ResourceKey<Item> SPECTRAL_ARROW;
   public static final ResourceKey<Item> TIPPED_ARROW;
   public static final ResourceKey<Item> LINGERING_POTION;
   public static final ResourceKey<Item> SHIELD;
   public static final ResourceKey<Item> WOODEN_SPEAR;
   public static final ResourceKey<Item> STONE_SPEAR;
   public static final ResourceKey<Item> COPPER_SPEAR;
   public static final ResourceKey<Item> IRON_SPEAR;
   public static final ResourceKey<Item> GOLDEN_SPEAR;
   public static final ResourceKey<Item> DIAMOND_SPEAR;
   public static final ResourceKey<Item> NETHERITE_SPEAR;
   public static final ResourceKey<Item> TOTEM_OF_UNDYING;
   public static final ResourceKey<Item> SHULKER_SHELL;
   public static final ResourceKey<Item> IRON_NUGGET;
   public static final ResourceKey<Item> COPPER_NUGGET;
   public static final ResourceKey<Item> KNOWLEDGE_BOOK;
   public static final ResourceKey<Item> DEBUG_STICK;
   public static final ResourceKey<Item> MUSIC_DISC_13;
   public static final ResourceKey<Item> MUSIC_DISC_CAT;
   public static final ResourceKey<Item> MUSIC_DISC_BLOCKS;
   public static final ResourceKey<Item> MUSIC_DISC_BOUNCE;
   public static final ResourceKey<Item> MUSIC_DISC_CHIRP;
   public static final ResourceKey<Item> MUSIC_DISC_CREATOR;
   public static final ResourceKey<Item> MUSIC_DISC_CREATOR_MUSIC_BOX;
   public static final ResourceKey<Item> MUSIC_DISC_FAR;
   public static final ResourceKey<Item> MUSIC_DISC_LAVA_CHICKEN;
   public static final ResourceKey<Item> MUSIC_DISC_MALL;
   public static final ResourceKey<Item> MUSIC_DISC_MELLOHI;
   public static final ResourceKey<Item> MUSIC_DISC_STAL;
   public static final ResourceKey<Item> MUSIC_DISC_STRAD;
   public static final ResourceKey<Item> MUSIC_DISC_WARD;
   public static final ResourceKey<Item> MUSIC_DISC_11;
   public static final ResourceKey<Item> MUSIC_DISC_WAIT;
   public static final ResourceKey<Item> MUSIC_DISC_OTHERSIDE;
   public static final ResourceKey<Item> MUSIC_DISC_RELIC;
   public static final ResourceKey<Item> MUSIC_DISC_5;
   public static final ResourceKey<Item> MUSIC_DISC_PIGSTEP;
   public static final ResourceKey<Item> MUSIC_DISC_PRECIPICE;
   public static final ResourceKey<Item> MUSIC_DISC_TEARS;
   public static final ResourceKey<Item> DISC_FRAGMENT_5;
   public static final ResourceKey<Item> TRIDENT;
   public static final ResourceKey<Item> NAUTILUS_SHELL;
   public static final ResourceKey<Item> IRON_NAUTILUS_ARMOR;
   public static final ResourceKey<Item> GOLDEN_NAUTILUS_ARMOR;
   public static final ResourceKey<Item> DIAMOND_NAUTILUS_ARMOR;
   public static final ResourceKey<Item> NETHERITE_NAUTILUS_ARMOR;
   public static final ResourceKey<Item> COPPER_NAUTILUS_ARMOR;
   public static final ResourceKey<Item> HEART_OF_THE_SEA;
   public static final ResourceKey<Item> CROSSBOW;
   public static final ResourceKey<Item> SUSPICIOUS_STEW;
   public static final ResourceKey<Item> FLOWER_BANNER_PATTERN;
   public static final ResourceKey<Item> CREEPER_BANNER_PATTERN;
   public static final ResourceKey<Item> SKULL_BANNER_PATTERN;
   public static final ResourceKey<Item> MOJANG_BANNER_PATTERN;
   public static final ResourceKey<Item> GLOBE_BANNER_PATTERN;
   public static final ResourceKey<Item> PIGLIN_BANNER_PATTERN;
   public static final ResourceKey<Item> FLOW_BANNER_PATTERN;
   public static final ResourceKey<Item> GUSTER_BANNER_PATTERN;
   public static final ResourceKey<Item> FIELD_MASONED_BANNER_PATTERN;
   public static final ResourceKey<Item> BORDURE_INDENTED_BANNER_PATTERN;
   public static final ResourceKey<Item> GOAT_HORN;
   public static final ResourceKey<Item> HONEYCOMB;
   public static final ResourceKey<Item> HONEY_BOTTLE;
   public static final ResourceKey<Item> ECHO_SHARD;
   public static final ResourceKey<Item> BRUSH;
   public static final String SMITHING_TEMPLATE_SUFFIX = "_smithing_template";
   public static final ResourceKey<Item> NETHERITE_UPGRADE_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> DUNE_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> COAST_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> WILD_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> WARD_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> EYE_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> VEX_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> TIDE_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> RIB_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> RAISER_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> HOST_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> FLOW_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> BOLT_ARMOR_TRIM_SMITHING_TEMPLATE;
   public static final ResourceKey<Item> ANGLER_POTTERY_SHERD;
   public static final ResourceKey<Item> ARCHER_POTTERY_SHERD;
   public static final ResourceKey<Item> ARMS_UP_POTTERY_SHERD;
   public static final ResourceKey<Item> BLADE_POTTERY_SHERD;
   public static final ResourceKey<Item> BREWER_POTTERY_SHERD;
   public static final ResourceKey<Item> BURN_POTTERY_SHERD;
   public static final ResourceKey<Item> DANGER_POTTERY_SHERD;
   public static final ResourceKey<Item> EXPLORER_POTTERY_SHERD;
   public static final ResourceKey<Item> FLOW_POTTERY_SHERD;
   public static final ResourceKey<Item> FRIEND_POTTERY_SHERD;
   public static final ResourceKey<Item> GUSTER_POTTERY_SHERD;
   public static final ResourceKey<Item> HEART_POTTERY_SHERD;
   public static final ResourceKey<Item> HEARTBREAK_POTTERY_SHERD;
   public static final ResourceKey<Item> HOWL_POTTERY_SHERD;
   public static final ResourceKey<Item> MINER_POTTERY_SHERD;
   public static final ResourceKey<Item> MOURNER_POTTERY_SHERD;
   public static final ResourceKey<Item> PLENTY_POTTERY_SHERD;
   public static final ResourceKey<Item> PRIZE_POTTERY_SHERD;
   public static final ResourceKey<Item> SCRAPE_POTTERY_SHERD;
   public static final ResourceKey<Item> SHEAF_POTTERY_SHERD;
   public static final ResourceKey<Item> SHELTER_POTTERY_SHERD;
   public static final ResourceKey<Item> SKULL_POTTERY_SHERD;
   public static final ResourceKey<Item> SNORT_POTTERY_SHERD;
   public static final ResourceKey<Item> TRIAL_KEY;
   public static final ResourceKey<Item> OMINOUS_TRIAL_KEY;
   public static final ResourceKey<Item> OMINOUS_BOTTLE;
   public static final ColorCollection<ResourceKey<Item>> HARNESS;
   public static final ColorCollection<ResourceKey<Item>> DYED_BUNDLE;
   public static final ColorCollection<ResourceKey<Item>> DYE;

   public ItemIds() {
      super();
   }

   private static ResourceKey<Item> create(final String name) {
      return ResourceKey.create(Registries.ITEM, Identifier.withDefaultNamespace(name));
   }

   private static ResourceKey<Item> createPotterySherd(final ResourceKey<DecoratedPotPattern> sherd) {
      return sherd.dependent(Registries.ITEM, "_pottery_sherd");
   }

   private static ResourceKey<Item> createArmorTrimSmithingTemplate(final ResourceKey<TrimPattern> template) {
      return template.dependent(Registries.ITEM, "_armor_trim_smithing_template");
   }

   private static ResourceKey<Item> createMusicDisc(final ResourceKey<JukeboxSong> music) {
      return music.dependent(Registries.ITEM, (UnaryOperator)((path) -> "music_disc_" + path));
   }

   private static ResourceKey<Item> createSpawnEgg(final ResourceKey<EntityType<?>> entity) {
      return entity.dependent(Registries.ITEM, "_spawn_egg");
   }

   private static ColorCollection<ResourceKey<Item>> createSimpleColored(final String baseName) {
      return ColorCollection.prefixWithColor(ColorCollection.create(baseName)).<ResourceKey<Item>>map(ItemIds::create);
   }

   static {
      CHICKEN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CHICKEN);
      COW_SPAWN_EGG = createSpawnEgg(EntityTypeIds.COW);
      PIG_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PIG);
      SHEEP_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SHEEP);
      CAMEL_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CAMEL);
      DONKEY_SPAWN_EGG = createSpawnEgg(EntityTypeIds.DONKEY);
      HORSE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.HORSE);
      MULE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.MULE);
      CAT_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CAT);
      PARROT_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PARROT);
      WOLF_SPAWN_EGG = createSpawnEgg(EntityTypeIds.WOLF);
      ARMADILLO_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ARMADILLO);
      BAT_SPAWN_EGG = createSpawnEgg(EntityTypeIds.BAT);
      BEE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.BEE);
      FOX_SPAWN_EGG = createSpawnEgg(EntityTypeIds.FOX);
      GOAT_SPAWN_EGG = createSpawnEgg(EntityTypeIds.GOAT);
      LLAMA_SPAWN_EGG = createSpawnEgg(EntityTypeIds.LLAMA);
      OCELOT_SPAWN_EGG = createSpawnEgg(EntityTypeIds.OCELOT);
      PANDA_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PANDA);
      POLAR_BEAR_SPAWN_EGG = createSpawnEgg(EntityTypeIds.POLAR_BEAR);
      RABBIT_SPAWN_EGG = createSpawnEgg(EntityTypeIds.RABBIT);
      AXOLOTL_SPAWN_EGG = createSpawnEgg(EntityTypeIds.AXOLOTL);
      COD_SPAWN_EGG = createSpawnEgg(EntityTypeIds.COD);
      DOLPHIN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.DOLPHIN);
      FROG_SPAWN_EGG = createSpawnEgg(EntityTypeIds.FROG);
      GLOW_SQUID_SPAWN_EGG = createSpawnEgg(EntityTypeIds.GLOW_SQUID);
      NAUTILUS_SPAWN_EGG = createSpawnEgg(EntityTypeIds.NAUTILUS);
      PUFFERFISH_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PUFFERFISH);
      SALMON_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SALMON);
      SQUID_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SQUID);
      TADPOLE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.TADPOLE);
      TROPICAL_FISH_SPAWN_EGG = createSpawnEgg(EntityTypeIds.TROPICAL_FISH);
      TURTLE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.TURTLE);
      ALLAY_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ALLAY);
      MOOSHROOM_SPAWN_EGG = createSpawnEgg(EntityTypeIds.MOOSHROOM);
      SNIFFER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SNIFFER);
      SULFUR_CUBE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SULFUR_CUBE);
      COPPER_GOLEM_SPAWN_EGG = createSpawnEgg(EntityTypeIds.COPPER_GOLEM);
      IRON_GOLEM_SPAWN_EGG = createSpawnEgg(EntityTypeIds.IRON_GOLEM);
      SNOW_GOLEM_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SNOW_GOLEM);
      TRADER_LLAMA_SPAWN_EGG = createSpawnEgg(EntityTypeIds.TRADER_LLAMA);
      VILLAGER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.VILLAGER);
      WANDERING_TRADER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.WANDERING_TRADER);
      BOGGED_SPAWN_EGG = createSpawnEgg(EntityTypeIds.BOGGED);
      CAMEL_HUSK_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CAMEL_HUSK);
      DROWNED_SPAWN_EGG = createSpawnEgg(EntityTypeIds.DROWNED);
      HUSK_SPAWN_EGG = createSpawnEgg(EntityTypeIds.HUSK);
      PARCHED_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PARCHED);
      SKELETON_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SKELETON);
      SKELETON_HORSE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SKELETON_HORSE);
      STRAY_SPAWN_EGG = createSpawnEgg(EntityTypeIds.STRAY);
      WITHER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.WITHER);
      WITHER_SKELETON_SPAWN_EGG = createSpawnEgg(EntityTypeIds.WITHER_SKELETON);
      ZOMBIE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ZOMBIE);
      ZOMBIE_HORSE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ZOMBIE_HORSE);
      ZOMBIE_NAUTILUS_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ZOMBIE_NAUTILUS);
      ZOMBIE_VILLAGER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ZOMBIE_VILLAGER);
      CAVE_SPIDER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CAVE_SPIDER);
      SPIDER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SPIDER);
      BREEZE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.BREEZE);
      CREAKING_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CREAKING);
      CREEPER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.CREEPER);
      ELDER_GUARDIAN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ELDER_GUARDIAN);
      GUARDIAN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.GUARDIAN);
      PHANTOM_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PHANTOM);
      SILVERFISH_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SILVERFISH);
      SLIME_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SLIME);
      WARDEN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.WARDEN);
      WITCH_SPAWN_EGG = createSpawnEgg(EntityTypeIds.WITCH);
      EVOKER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.EVOKER);
      PILLAGER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PILLAGER);
      RAVAGER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.RAVAGER);
      VINDICATOR_SPAWN_EGG = createSpawnEgg(EntityTypeIds.VINDICATOR);
      VEX_SPAWN_EGG = createSpawnEgg(EntityTypeIds.VEX);
      BLAZE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.BLAZE);
      GHAST_SPAWN_EGG = createSpawnEgg(EntityTypeIds.GHAST);
      HAPPY_GHAST_SPAWN_EGG = createSpawnEgg(EntityTypeIds.HAPPY_GHAST);
      HOGLIN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.HOGLIN);
      MAGMA_CUBE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.MAGMA_CUBE);
      PIGLIN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PIGLIN);
      PIGLIN_BRUTE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.PIGLIN_BRUTE);
      STRIDER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.STRIDER);
      ZOGLIN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ZOGLIN);
      ZOMBIFIED_PIGLIN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ZOMBIFIED_PIGLIN);
      ENDER_DRAGON_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ENDER_DRAGON);
      ENDERMAN_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ENDERMAN);
      ENDERMITE_SPAWN_EGG = createSpawnEgg(EntityTypeIds.ENDERMITE);
      SHULKER_SPAWN_EGG = createSpawnEgg(EntityTypeIds.SHULKER);
      EXPERIENCE_BOTTLE = create("experience_bottle");
      FIRE_CHARGE = create("fire_charge");
      WIND_CHARGE = create("wind_charge");
      WRITABLE_BOOK = create("writable_book");
      WRITTEN_BOOK = create("written_book");
      BREEZE_ROD = create("breeze_rod");
      MACE = create("mace");
      ITEM_FRAME = create("item_frame");
      GLOW_ITEM_FRAME = create("glow_item_frame");
      BAKED_POTATO = create("baked_potato");
      POISONOUS_POTATO = create("poisonous_potato");
      MAP = create("map");
      GOLDEN_CARROT = create("golden_carrot");
      NETHER_STAR = create("nether_star");
      PUMPKIN_PIE = create("pumpkin_pie");
      FIREWORK_ROCKET = create("firework_rocket");
      FIREWORK_STAR = create("firework_star");
      ENCHANTED_BOOK = create("enchanted_book");
      NETHER_BRICK = create("nether_brick");
      RESIN_BRICK = create("resin_brick");
      PRISMARINE_SHARD = create("prismarine_shard");
      PRISMARINE_CRYSTALS = create("prismarine_crystals");
      RABBIT = create("rabbit");
      COOKED_RABBIT = create("cooked_rabbit");
      RABBIT_STEW = create("rabbit_stew");
      RABBIT_FOOT = create("rabbit_foot");
      RABBIT_HIDE = create("rabbit_hide");
      ARMOR_STAND = create("armor_stand");
      COPPER_HORSE_ARMOR = create("copper_horse_armor");
      IRON_HORSE_ARMOR = create("iron_horse_armor");
      GOLDEN_HORSE_ARMOR = create("golden_horse_armor");
      DIAMOND_HORSE_ARMOR = create("diamond_horse_armor");
      NETHERITE_HORSE_ARMOR = create("netherite_horse_armor");
      LEATHER_HORSE_ARMOR = create("leather_horse_armor");
      LEAD = create("lead");
      NAME_TAG = create("name_tag");
      COMMAND_BLOCK_MINECART = create("command_block_minecart");
      MUTTON = create("mutton");
      COOKED_MUTTON = create("cooked_mutton");
      END_CRYSTAL = create("end_crystal");
      CHORUS_FRUIT = create("chorus_fruit");
      POPPED_CHORUS_FRUIT = create("popped_chorus_fruit");
      BEETROOT = create("beetroot");
      BEETROOT_SOUP = create("beetroot_soup");
      DRAGON_BREATH = create("dragon_breath");
      SPLASH_POTION = create("splash_potion");
      SPECTRAL_ARROW = create("spectral_arrow");
      TIPPED_ARROW = create("tipped_arrow");
      LINGERING_POTION = create("lingering_potion");
      SHIELD = create("shield");
      WOODEN_SPEAR = create("wooden_spear");
      STONE_SPEAR = create("stone_spear");
      COPPER_SPEAR = create("copper_spear");
      IRON_SPEAR = create("iron_spear");
      GOLDEN_SPEAR = create("golden_spear");
      DIAMOND_SPEAR = create("diamond_spear");
      NETHERITE_SPEAR = create("netherite_spear");
      TOTEM_OF_UNDYING = create("totem_of_undying");
      SHULKER_SHELL = create("shulker_shell");
      IRON_NUGGET = create("iron_nugget");
      COPPER_NUGGET = create("copper_nugget");
      KNOWLEDGE_BOOK = create("knowledge_book");
      DEBUG_STICK = create("debug_stick");
      MUSIC_DISC_13 = createMusicDisc(JukeboxSongs.THIRTEEN);
      MUSIC_DISC_CAT = createMusicDisc(JukeboxSongs.CAT);
      MUSIC_DISC_BLOCKS = createMusicDisc(JukeboxSongs.BLOCKS);
      MUSIC_DISC_BOUNCE = createMusicDisc(JukeboxSongs.BOUNCE);
      MUSIC_DISC_CHIRP = createMusicDisc(JukeboxSongs.CHIRP);
      MUSIC_DISC_CREATOR = createMusicDisc(JukeboxSongs.CREATOR);
      MUSIC_DISC_CREATOR_MUSIC_BOX = createMusicDisc(JukeboxSongs.CREATOR_MUSIC_BOX);
      MUSIC_DISC_FAR = createMusicDisc(JukeboxSongs.FAR);
      MUSIC_DISC_LAVA_CHICKEN = createMusicDisc(JukeboxSongs.LAVA_CHICKEN);
      MUSIC_DISC_MALL = createMusicDisc(JukeboxSongs.MALL);
      MUSIC_DISC_MELLOHI = createMusicDisc(JukeboxSongs.MELLOHI);
      MUSIC_DISC_STAL = createMusicDisc(JukeboxSongs.STAL);
      MUSIC_DISC_STRAD = createMusicDisc(JukeboxSongs.STRAD);
      MUSIC_DISC_WARD = createMusicDisc(JukeboxSongs.WARD);
      MUSIC_DISC_11 = createMusicDisc(JukeboxSongs.ELEVEN);
      MUSIC_DISC_WAIT = createMusicDisc(JukeboxSongs.WAIT);
      MUSIC_DISC_OTHERSIDE = createMusicDisc(JukeboxSongs.OTHERSIDE);
      MUSIC_DISC_RELIC = createMusicDisc(JukeboxSongs.RELIC);
      MUSIC_DISC_5 = createMusicDisc(JukeboxSongs.FIVE);
      MUSIC_DISC_PIGSTEP = createMusicDisc(JukeboxSongs.PIGSTEP);
      MUSIC_DISC_PRECIPICE = createMusicDisc(JukeboxSongs.PRECIPICE);
      MUSIC_DISC_TEARS = createMusicDisc(JukeboxSongs.TEARS);
      DISC_FRAGMENT_5 = create("disc_fragment_5");
      TRIDENT = create("trident");
      NAUTILUS_SHELL = create("nautilus_shell");
      IRON_NAUTILUS_ARMOR = create("iron_nautilus_armor");
      GOLDEN_NAUTILUS_ARMOR = create("golden_nautilus_armor");
      DIAMOND_NAUTILUS_ARMOR = create("diamond_nautilus_armor");
      NETHERITE_NAUTILUS_ARMOR = create("netherite_nautilus_armor");
      COPPER_NAUTILUS_ARMOR = create("copper_nautilus_armor");
      HEART_OF_THE_SEA = create("heart_of_the_sea");
      CROSSBOW = create("crossbow");
      SUSPICIOUS_STEW = create("suspicious_stew");
      FLOWER_BANNER_PATTERN = create("flower_banner_pattern");
      CREEPER_BANNER_PATTERN = create("creeper_banner_pattern");
      SKULL_BANNER_PATTERN = create("skull_banner_pattern");
      MOJANG_BANNER_PATTERN = create("mojang_banner_pattern");
      GLOBE_BANNER_PATTERN = create("globe_banner_pattern");
      PIGLIN_BANNER_PATTERN = create("piglin_banner_pattern");
      FLOW_BANNER_PATTERN = create("flow_banner_pattern");
      GUSTER_BANNER_PATTERN = create("guster_banner_pattern");
      FIELD_MASONED_BANNER_PATTERN = create("field_masoned_banner_pattern");
      BORDURE_INDENTED_BANNER_PATTERN = create("bordure_indented_banner_pattern");
      GOAT_HORN = create("goat_horn");
      HONEYCOMB = create("honeycomb");
      HONEY_BOTTLE = create("honey_bottle");
      ECHO_SHARD = create("echo_shard");
      BRUSH = create("brush");
      NETHERITE_UPGRADE_SMITHING_TEMPLATE = create("netherite_upgrade_smithing_template");
      SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.SENTRY);
      DUNE_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.DUNE);
      COAST_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.COAST);
      WILD_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.WILD);
      WARD_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.WARD);
      EYE_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.EYE);
      VEX_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.VEX);
      TIDE_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.TIDE);
      SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.SNOUT);
      RIB_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.RIB);
      SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.SPIRE);
      WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.WAYFINDER);
      SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.SHAPER);
      SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.SILENCE);
      RAISER_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.RAISER);
      HOST_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.HOST);
      FLOW_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.FLOW);
      BOLT_ARMOR_TRIM_SMITHING_TEMPLATE = createArmorTrimSmithingTemplate(TrimPatterns.BOLT);
      ANGLER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.ANGLER);
      ARCHER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.ARCHER);
      ARMS_UP_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.ARMS_UP);
      BLADE_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.BLADE);
      BREWER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.BREWER);
      BURN_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.BURN);
      DANGER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.DANGER);
      EXPLORER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.EXPLORER);
      FLOW_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.FLOW);
      FRIEND_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.FRIEND);
      GUSTER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.GUSTER);
      HEART_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.HEART);
      HEARTBREAK_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.HEARTBREAK);
      HOWL_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.HOWL);
      MINER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.MINER);
      MOURNER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.MOURNER);
      PLENTY_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.PLENTY);
      PRIZE_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.PRIZE);
      SCRAPE_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.SCRAPE);
      SHEAF_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.SHEAF);
      SHELTER_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.SHELTER);
      SKULL_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.SKULL);
      SNORT_POTTERY_SHERD = createPotterySherd(DecoratedPotPatterns.SNORT);
      TRIAL_KEY = create("trial_key");
      OMINOUS_TRIAL_KEY = create("ominous_trial_key");
      OMINOUS_BOTTLE = create("ominous_bottle");
      HARNESS = createSimpleColored("harness");
      DYED_BUNDLE = createSimpleColored("bundle");
      DYE = createSimpleColored("dye");
   }
}
