package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import net.minecraft.client.model.AbstractEquineModel;
import net.minecraft.client.model.AllayModel;
import net.minecraft.client.model.ArmadilloModel;
import net.minecraft.client.model.ArmorStandArmorModel;
import net.minecraft.client.model.ArmorStandModel;
import net.minecraft.client.model.ArrowModel;
import net.minecraft.client.model.AxolotlModel;
import net.minecraft.client.model.BannerFlagModel;
import net.minecraft.client.model.BannerModel;
import net.minecraft.client.model.BatModel;
import net.minecraft.client.model.BeeModel;
import net.minecraft.client.model.BeeStingerModel;
import net.minecraft.client.model.BellModel;
import net.minecraft.client.model.BlazeModel;
import net.minecraft.client.model.BoatModel;
import net.minecraft.client.model.BoggedModel;
import net.minecraft.client.model.BookModel;
import net.minecraft.client.model.BreezeModel;
import net.minecraft.client.model.CamelModel;
import net.minecraft.client.model.CamelSaddleModel;
import net.minecraft.client.model.CatModel;
import net.minecraft.client.model.ChestModel;
import net.minecraft.client.model.ChickenModel;
import net.minecraft.client.model.CodModel;
import net.minecraft.client.model.ColdChickenModel;
import net.minecraft.client.model.ColdCowModel;
import net.minecraft.client.model.ColdPigModel;
import net.minecraft.client.model.CopperGolemModel;
import net.minecraft.client.model.CowModel;
import net.minecraft.client.model.CreakingModel;
import net.minecraft.client.model.CreeperModel;
import net.minecraft.client.model.DolphinModel;
import net.minecraft.client.model.DonkeyModel;
import net.minecraft.client.model.DrownedModel;
import net.minecraft.client.model.ElytraModel;
import net.minecraft.client.model.EndCrystalModel;
import net.minecraft.client.model.EndermanModel;
import net.minecraft.client.model.EndermiteModel;
import net.minecraft.client.model.EquineSaddleModel;
import net.minecraft.client.model.EvokerFangsModel;
import net.minecraft.client.model.FelineModel;
import net.minecraft.client.model.FoxModel;
import net.minecraft.client.model.FrogModel;
import net.minecraft.client.model.GhastModel;
import net.minecraft.client.model.GoatModel;
import net.minecraft.client.model.GuardianModel;
import net.minecraft.client.model.HappyGhastHarnessModel;
import net.minecraft.client.model.HappyGhastModel;
import net.minecraft.client.model.HoglinModel;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.IllagerModel;
import net.minecraft.client.model.IronGolemModel;
import net.minecraft.client.model.LavaSlimeModel;
import net.minecraft.client.model.LeashKnotModel;
import net.minecraft.client.model.LlamaModel;
import net.minecraft.client.model.LlamaSpitModel;
import net.minecraft.client.model.MinecartModel;
import net.minecraft.client.model.NautilusArmorModel;
import net.minecraft.client.model.NautilusModel;
import net.minecraft.client.model.NautilusSaddleModel;
import net.minecraft.client.model.PandaModel;
import net.minecraft.client.model.ParrotModel;
import net.minecraft.client.model.PhantomModel;
import net.minecraft.client.model.PigModel;
import net.minecraft.client.model.PiglinHeadModel;
import net.minecraft.client.model.PiglinModel;
import net.minecraft.client.model.PlayerCapeModel;
import net.minecraft.client.model.PlayerEarsModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.PolarBearModel;
import net.minecraft.client.model.PufferfishBigModel;
import net.minecraft.client.model.PufferfishMidModel;
import net.minecraft.client.model.PufferfishSmallModel;
import net.minecraft.client.model.RabbitModel;
import net.minecraft.client.model.RaftModel;
import net.minecraft.client.model.RavagerModel;
import net.minecraft.client.model.SalmonModel;
import net.minecraft.client.model.SheepFurModel;
import net.minecraft.client.model.SheepModel;
import net.minecraft.client.model.ShieldModel;
import net.minecraft.client.model.ShulkerBulletModel;
import net.minecraft.client.model.ShulkerModel;
import net.minecraft.client.model.SilverfishModel;
import net.minecraft.client.model.SkeletonModel;
import net.minecraft.client.model.SkullModel;
import net.minecraft.client.model.SlimeModel;
import net.minecraft.client.model.SnifferModel;
import net.minecraft.client.model.SnowGolemModel;
import net.minecraft.client.model.SpiderModel;
import net.minecraft.client.model.SpinAttackEffectModel;
import net.minecraft.client.model.SquidModel;
import net.minecraft.client.model.StriderModel;
import net.minecraft.client.model.TadpoleModel;
import net.minecraft.client.model.TridentModel;
import net.minecraft.client.model.TropicalFishModelA;
import net.minecraft.client.model.TropicalFishModelB;
import net.minecraft.client.model.TurtleModel;
import net.minecraft.client.model.VexModel;
import net.minecraft.client.model.VillagerModel;
import net.minecraft.client.model.WardenModel;
import net.minecraft.client.model.WarmCowModel;
import net.minecraft.client.model.WindChargeModel;
import net.minecraft.client.model.WitchModel;
import net.minecraft.client.model.WitherBossModel;
import net.minecraft.client.model.WolfModel;
import net.minecraft.client.model.ZombieVillagerModel;
import net.minecraft.client.model.dragon.DragonHeadModel;
import net.minecraft.client.model.dragon.EnderDragonModel;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.ArmorModelSet;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.state.properties.WoodType;

public class LayerDefinitions {
   private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);
   private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);
   private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);

   public LayerDefinitions() {
      super();
   }

   public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
      ImmutableMap.Builder var0 = ImmutableMap.builder();
      LayerDefinition var1 = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
      ArmorModelSet var2 = HumanoidModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map((var0x) -> LayerDefinition.create(var0x, 64, 32));
      ArmorModelSet var3 = var2.map((var0x) -> var0x.apply(HumanoidModel.BABY_TRANSFORMER));
      ArmorModelSet var4 = PlayerModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map((var0x) -> LayerDefinition.create(var0x, 64, 32));
      ArmorModelSet var5 = PiglinModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, new CubeDeformation(1.02F)).map((var0x) -> LayerDefinition.create(var0x, 64, 32));
      ArmorModelSet var6 = var5.map((var0x) -> var0x.apply(HumanoidModel.BABY_TRANSFORMER));
      LayerDefinition var7 = MinecartModel.createBodyLayer();
      LayerDefinition var8 = SkullModel.createMobHeadLayer();
      LayerDefinition var9 = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
      LayerDefinition var10 = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
      LayerDefinition var11 = EquineSaddleModel.createSaddleLayer(false);
      LayerDefinition var12 = EquineSaddleModel.createSaddleLayer(true);
      MeshTransformer var13 = MeshTransformer.scaling(0.9375F);
      LayerDefinition var14 = IllagerModel.createBodyLayer().apply(var13);
      LayerDefinition var15 = AxolotlModel.createBodyLayer();
      LayerDefinition var16 = BeeModel.createBodyLayer();
      LayerDefinition var17 = CowModel.createBodyLayer();
      LayerDefinition var18 = ColdChickenModel.createBodyLayer();
      LayerDefinition var19 = ColdCowModel.createBodyLayer();
      LayerDefinition var20 = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
      LayerDefinition var21 = ElytraModel.createLayer();
      LayerDefinition var22 = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
      LayerDefinition var23 = var22.apply(FelineModel.BABY_TRANSFORMER);
      LayerDefinition var24 = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32);
      LayerDefinition var25 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
      LayerDefinition var26 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
      LayerDefinition var27 = SkullModel.createHumanoidHeadLayer();
      LayerDefinition var28 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
      LayerDefinition var29 = LlamaModel.createBodyLayer(new CubeDeformation(0.5F));
      LayerDefinition var30 = StriderModel.createBodyLayer();
      LayerDefinition var31 = HoglinModel.createBodyLayer();
      LayerDefinition var32 = HoglinModel.createBabyLayer();
      LayerDefinition var33 = SkeletonModel.createBodyLayer();
      LayerDefinition var34 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(var13);
      LayerDefinition var35 = LayerDefinition.create(VillagerModel.createNoHatModel(), 64, 64).apply(var13);
      LayerDefinition var36 = SpiderModel.createSpiderBodyLayer();
      LayerDefinition var37 = ArmadilloModel.createBodyLayer();
      LayerDefinition var38 = CamelModel.createBodyLayer();
      LayerDefinition var39 = CamelSaddleModel.createSaddleLayer();
      LayerDefinition var40 = ChickenModel.createBodyLayer();
      LayerDefinition var41 = GoatModel.createBodyLayer();
      LayerDefinition var42 = PandaModel.createBodyLayer();
      LayerDefinition var43 = PigModel.createBodyLayer(CubeDeformation.NONE);
      LayerDefinition var44 = PigModel.createBodyLayer(new CubeDeformation(0.5F));
      LayerDefinition var45 = SheepModel.createBodyLayer();
      LayerDefinition var46 = SheepFurModel.createFurLayer();
      LayerDefinition var47 = SnifferModel.createBodyLayer();
      LayerDefinition var48 = TurtleModel.createBodyLayer();
      LayerDefinition var49 = WarmCowModel.createBodyLayer();
      LayerDefinition var50 = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
      LayerDefinition var51 = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2F)), 64, 32);
      LayerDefinition var52 = ZombieVillagerModel.createBodyLayer();
      LayerDefinition var53 = ZombieVillagerModel.createNoHatLayer();
      LayerDefinition var54 = ArmorStandModel.createBodyLayer();
      ArmorModelSet var55 = ArmorStandArmorModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
      LayerDefinition var56 = DrownedModel.createBodyLayer(CubeDeformation.NONE);
      LayerDefinition var57 = DrownedModel.createBodyLayer(new CubeDeformation(0.25F));
      LayerDefinition var58 = SquidModel.createBodyLayer();
      LayerDefinition var59 = DolphinModel.createBodyLayer();
      LayerDefinition var60 = SalmonModel.createBodyLayer();
      LayerDefinition var61 = NautilusSaddleModel.createSaddleLayer();
      var0.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
      var0.put(ModelLayers.ARMADILLO, var37);
      var0.put(ModelLayers.ARMADILLO_BABY, var37.apply(ArmadilloModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.ARMOR_STAND, var54);
      ModelLayers.ARMOR_STAND_ARMOR.putFrom(var55, var0);
      var0.put(ModelLayers.ARMOR_STAND_SMALL, var54.apply(HumanoidModel.BABY_TRANSFORMER));
      ModelLayers.ARMOR_STAND_SMALL_ARMOR.putFrom(var55.map((var0x) -> var0x.apply(HumanoidModel.BABY_TRANSFORMER)), var0);
      var0.put(ModelLayers.ARROW, ArrowModel.createBodyLayer());
      var0.put(ModelLayers.AXOLOTL, var15);
      var0.put(ModelLayers.AXOLOTL_BABY, var15.apply(AxolotlModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.STANDING_BANNER, BannerModel.createBodyLayer(true));
      var0.put(ModelLayers.WALL_BANNER, BannerModel.createBodyLayer(false));
      var0.put(ModelLayers.STANDING_BANNER_FLAG, BannerFlagModel.createFlagLayer(true));
      var0.put(ModelLayers.WALL_BANNER_FLAG, BannerFlagModel.createFlagLayer(false));
      var0.put(ModelLayers.BAT, BatModel.createBodyLayer());
      var0.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
      var0.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
      var0.put(ModelLayers.BEE, var16);
      var0.put(ModelLayers.BEE_BABY, var16.apply(BeeModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.BEE_STINGER, BeeStingerModel.createBodyLayer());
      var0.put(ModelLayers.BELL, BellModel.createBodyLayer());
      var0.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
      var0.put(ModelLayers.BOAT_WATER_PATCH, BoatModel.createWaterPatch());
      var0.put(ModelLayers.BOGGED, BoggedModel.createBodyLayer());
      ModelLayers.BOGGED_ARMOR.putFrom(var2, var0);
      var0.put(ModelLayers.BOGGED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2F), 0.0F), 64, 32));
      var0.put(ModelLayers.BOOK, BookModel.createBodyLayer());
      var0.put(ModelLayers.BREEZE, BreezeModel.createBodyLayer());
      var0.put(ModelLayers.BREEZE_WIND, BreezeModel.createWindLayer());
      var0.put(ModelLayers.BREEZE_EYES, BreezeModel.createEyesLayer());
      var0.put(ModelLayers.CAT, var22.apply(CatModel.CAT_TRANSFORMER));
      var0.put(ModelLayers.CAT_BABY, var23.apply(CatModel.CAT_TRANSFORMER));
      var0.put(ModelLayers.CAT_COLLAR, var24.apply(CatModel.CAT_TRANSFORMER));
      var0.put(ModelLayers.CAT_BABY_COLLAR, var24.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
      var0.put(ModelLayers.CAMEL, var38);
      var0.put(ModelLayers.CAMEL_BABY, var38.apply(CamelModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.CAMEL_SADDLE, var39);
      var0.put(ModelLayers.CAMEL_BABY_SADDLE, var39.apply(CamelModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.CAVE_SPIDER, var36.apply(MeshTransformer.scaling(0.7F)));
      var0.put(ModelLayers.CHEST, ChestModel.createSingleBodyLayer());
      var0.put(ModelLayers.CHEST_MINECART, var7);
      var0.put(ModelLayers.CHICKEN, var40);
      var0.put(ModelLayers.CHICKEN_BABY, var40.apply(ChickenModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.COD, CodModel.createBodyLayer());
      var0.put(ModelLayers.COLD_CHICKEN, var18);
      var0.put(ModelLayers.COLD_CHICKEN_BABY, var18.apply(ChickenModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.COLD_COW, var19);
      var0.put(ModelLayers.COLD_COW_BABY, var19.apply(CowModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.COLD_PIG, var20);
      var0.put(ModelLayers.COLD_PIG_BABY, var20.apply(PigModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.COMMAND_BLOCK_MINECART, var7);
      var0.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
      var0.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
      var0.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
      var0.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
      var0.put(ModelLayers.COPPER_GOLEM, CopperGolemModel.createBodyLayer());
      var0.put(ModelLayers.COPPER_GOLEM_EYES, CopperGolemModel.createEyesLayer());
      var0.put(ModelLayers.COPPER_GOLEM_RUNNING, CopperGolemModel.createRunningPoseBodyLayer());
      var0.put(ModelLayers.COPPER_GOLEM_SITTING, CopperGolemModel.createSittingPoseBodyLayer());
      var0.put(ModelLayers.COPPER_GOLEM_STAR, CopperGolemModel.createStarPoseBodyLayer());
      var0.put(ModelLayers.COW, var17);
      var0.put(ModelLayers.COW_BABY, var17.apply(CowModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.CREAKING, CreakingModel.createBodyLayer());
      var0.put(ModelLayers.CREAKING_EYES, CreakingModel.createEyesLayer());
      var0.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
      var0.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
      var0.put(ModelLayers.CREEPER_HEAD, var8);
      var0.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
      var0.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
      var0.put(ModelLayers.DOLPHIN, var59);
      var0.put(ModelLayers.DOLPHIN_BABY, var59.apply(DolphinModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.DONKEY, DonkeyModel.createBodyLayer(0.87F));
      var0.put(ModelLayers.DONKEY_BABY, DonkeyModel.createBabyLayer(0.87F));
      var0.put(ModelLayers.DONKEY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, false));
      var0.put(ModelLayers.DONKEY_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, true));
      var0.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestModel.createDoubleBodyLeftLayer());
      var0.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestModel.createDoubleBodyRightLayer());
      var0.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
      var0.put(ModelLayers.DROWNED, var56);
      ModelLayers.DROWNED_ARMOR.putFrom(var2, var0);
      var0.put(ModelLayers.DROWNED_OUTER_LAYER, var57);
      var0.put(ModelLayers.DROWNED_BABY, var56.apply(HumanoidModel.BABY_TRANSFORMER));
      ModelLayers.DROWNED_BABY_ARMOR.putFrom(var3, var0);
      var0.put(ModelLayers.DROWNED_BABY_OUTER_LAYER, var57.apply(HumanoidModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createElderGuardianLayer());
      var0.put(ModelLayers.ELYTRA, var21);
      var0.put(ModelLayers.ELYTRA_BABY, var21.apply(ElytraModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
      var0.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
      var0.put(ModelLayers.ENDER_DRAGON, EnderDragonModel.createBodyLayer());
      var0.put(ModelLayers.END_CRYSTAL, EndCrystalModel.createBodyLayer());
      var0.put(ModelLayers.EVOKER, var14);
      var0.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
      var0.put(ModelLayers.FOX, FoxModel.createBodyLayer());
      var0.put(ModelLayers.FOX_BABY, FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.FROG, FrogModel.createBodyLayer());
      var0.put(ModelLayers.FURNACE_MINECART, var7);
      var0.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
      MeshTransformer var62 = MeshTransformer.scaling(6.0F);
      var0.put(ModelLayers.GIANT, var1.apply(var62));
      ModelLayers.GIANT_ARMOR.putFrom(var2.map((var1x) -> var1x.apply(var62)), var0);
      var0.put(ModelLayers.GLOW_SQUID, var58);
      var0.put(ModelLayers.GLOW_SQUID_BABY, var58.apply(SquidModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.GOAT, var41);
      var0.put(ModelLayers.GOAT_BABY, var41.apply(GoatModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
      var0.put(ModelLayers.HAPPY_GHAST, HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
      var0.put(ModelLayers.HAPPY_GHAST_BABY, HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.HAPPY_GHAST_HARNESS, HappyGhastHarnessModel.createHarnessLayer(false));
      var0.put(ModelLayers.HAPPY_GHAST_BABY_HARNESS, HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.HAPPY_GHAST_ROPES, HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2F)));
      var0.put(ModelLayers.HAPPY_GHAST_BABY_ROPES, HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2F)).apply(HappyGhastModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.HOGLIN, var31);
      var0.put(ModelLayers.HOGLIN_BABY, var32);
      var0.put(ModelLayers.HOPPER_MINECART, var7);
      MeshTransformer var63 = MeshTransformer.scaling(1.1F);
      var0.put(ModelLayers.HORSE, var9.apply(var63));
      var0.put(ModelLayers.HORSE_BABY, var10.apply(var63));
      var0.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64).apply(var63));
      var0.put(ModelLayers.HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64).apply(var63));
      var0.put(ModelLayers.HORSE_SADDLE, var11.apply(var63));
      var0.put(ModelLayers.HORSE_BABY_SADDLE, var12.apply(var63));
      MeshTransformer var64 = MeshTransformer.scaling(1.0625F);
      var0.put(ModelLayers.HUSK, var1.apply(var64));
      ModelLayers.HUSK_ARMOR.putFrom(var2.map((var1x) -> var1x.apply(var64)), var0);
      var0.put(ModelLayers.HUSK_BABY, var1.apply(HumanoidModel.BABY_TRANSFORMER).apply(var64));
      ModelLayers.HUSK_BABY_ARMOR.putFrom(var3.map((var1x) -> var1x.apply(var64)), var0);
      var0.put(ModelLayers.ILLUSIONER, var14);
      var0.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
      var0.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
      var0.put(ModelLayers.LLAMA, var28);
      var0.put(ModelLayers.LLAMA_BABY, var28.apply(LlamaModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.LLAMA_DECOR, var29);
      var0.put(ModelLayers.LLAMA_BABY_DECOR, var29.apply(LlamaModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
      var0.put(ModelLayers.MAGMA_CUBE, LavaSlimeModel.createBodyLayer());
      var0.put(ModelLayers.MINECART, var7);
      var0.put(ModelLayers.MOOSHROOM, var17);
      var0.put(ModelLayers.MOOSHROOM_BABY, var17.apply(CowModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.MULE, DonkeyModel.createBodyLayer(0.92F));
      var0.put(ModelLayers.MULE_BABY, DonkeyModel.createBabyLayer(0.92F));
      var0.put(ModelLayers.MULE_SADDLE, DonkeyModel.createSaddleLayer(0.92F, false));
      var0.put(ModelLayers.MULE_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.92F, true));
      var0.put(ModelLayers.NAUTILUS, NautilusModel.createBodyLayer());
      var0.put(ModelLayers.NAUTILUS_BABY, NautilusModel.createBabyBodyLayer());
      var0.put(ModelLayers.NAUTILUS_SADDLE, var61);
      var0.put(ModelLayers.NAUTILUS_ARMOR, NautilusArmorModel.createBodyLayer());
      var0.put(ModelLayers.ZOMBIE_NAUTILUS, NautilusModel.createBodyLayer());
      var0.put(ModelLayers.OCELOT, var22);
      var0.put(ModelLayers.OCELOT_BABY, var23);
      var0.put(ModelLayers.PANDA, var42);
      var0.put(ModelLayers.PANDA_BABY, var42.apply(PandaModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
      var0.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
      var0.put(ModelLayers.PIG, var43);
      var0.put(ModelLayers.PIG_BABY, var43.apply(PigModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.PIG_SADDLE, var44);
      var0.put(ModelLayers.PIG_BABY_SADDLE, var44.apply(PigModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.PIGLIN, var25);
      ModelLayers.PIGLIN_ARMOR.putFrom(var5, var0);
      var0.put(ModelLayers.PIGLIN_BRUTE, var25);
      ModelLayers.PIGLIN_BRUTE_ARMOR.putFrom(var5, var0);
      var0.put(ModelLayers.PIGLIN_BABY, var25.apply(HumanoidModel.BABY_TRANSFORMER));
      ModelLayers.PIGLIN_BABY_ARMOR.putFrom(var6, var0);
      var0.put(ModelLayers.PIGLIN_HEAD, var26);
      var0.put(ModelLayers.PILLAGER, var14);
      var0.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
      var0.put(ModelLayers.PLAYER_EARS, PlayerEarsModel.createEarsLayer());
      var0.put(ModelLayers.PLAYER_CAPE, PlayerCapeModel.createCapeLayer());
      var0.put(ModelLayers.PLAYER_HEAD, var27);
      ModelLayers.PLAYER_ARMOR.putFrom(var4, var0);
      var0.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
      ModelLayers.PLAYER_SLIM_ARMOR.putFrom(var4, var0);
      var0.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectModel.createLayer());
      var0.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer(false));
      var0.put(ModelLayers.POLAR_BEAR_BABY, PolarBearModel.createBodyLayer(true));
      var0.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
      var0.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
      var0.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
      var0.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer(false));
      var0.put(ModelLayers.RABBIT_BABY, RabbitModel.createBodyLayer(true));
      var0.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
      var0.put(ModelLayers.SALMON, var60);
      var0.put(ModelLayers.SALMON_SMALL, var60.apply(SalmonModel.SMALL_TRANSFORMER));
      var0.put(ModelLayers.SALMON_LARGE, var60.apply(SalmonModel.LARGE_TRANSFORMER));
      var0.put(ModelLayers.SHEEP, var45);
      var0.put(ModelLayers.SHEEP_BABY, var45.apply(SheepModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.SHEEP_WOOL, var46);
      var0.put(ModelLayers.SHEEP_BABY_WOOL, var46.apply(SheepModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.SHEEP_WOOL_UNDERCOAT, var45);
      var0.put(ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, var45.apply(SheepModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.SHIELD, ShieldModel.createLayer());
      var0.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
      var0.put(ModelLayers.SHULKER_BOX, ShulkerModel.createBoxLayer());
      var0.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
      var0.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
      var0.put(ModelLayers.SKELETON, var33);
      ModelLayers.SKELETON_ARMOR.putFrom(var2, var0);
      var0.put(ModelLayers.SKELETON_HORSE, var9);
      var0.put(ModelLayers.SKELETON_HORSE_BABY, var10);
      var0.put(ModelLayers.SKELETON_HORSE_SADDLE, var11);
      var0.put(ModelLayers.SKELETON_HORSE_BABY_SADDLE, var12);
      var0.put(ModelLayers.SKELETON_SKULL, var8);
      var0.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
      var0.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
      var0.put(ModelLayers.SNIFFER, var47);
      var0.put(ModelLayers.SNIFFER_BABY, var47.apply(SnifferModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
      var0.put(ModelLayers.SPAWNER_MINECART, var7);
      var0.put(ModelLayers.SPIDER, var36);
      var0.put(ModelLayers.SQUID, var58);
      var0.put(ModelLayers.SQUID_BABY, var58.apply(SquidModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.STRAY, var33);
      ModelLayers.STRAY_ARMOR.putFrom(var2, var0);
      var0.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
      var0.put(ModelLayers.STRIDER, var30);
      var0.put(ModelLayers.STRIDER_SADDLE, var30);
      var0.put(ModelLayers.STRIDER_BABY, var30.apply(StriderModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.STRIDER_BABY_SADDLE, var30.apply(StriderModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
      var0.put(ModelLayers.TNT_MINECART, var7);
      var0.put(ModelLayers.TRADER_LLAMA, var28);
      var0.put(ModelLayers.TRADER_LLAMA_BABY, var28.apply(LlamaModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.TRIDENT, TridentModel.createLayer());
      var0.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
      var0.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
      var0.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
      var0.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
      var0.put(ModelLayers.TURTLE, var48);
      var0.put(ModelLayers.TURTLE_BABY, var48.apply(TurtleModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.UNDEAD_HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
      var0.put(ModelLayers.UNDEAD_HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64));
      var0.put(ModelLayers.VEX, VexModel.createBodyLayer());
      var0.put(ModelLayers.VILLAGER, var34);
      var0.put(ModelLayers.VILLAGER_NO_HAT, var35);
      var0.put(ModelLayers.VILLAGER_BABY, var34.apply(VillagerModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.VILLAGER_BABY_NO_HAT, var35.apply(VillagerModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.VINDICATOR, var14);
      var0.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
      var0.put(ModelLayers.WARDEN_TENDRILS, WardenModel.createTendrilsLayer());
      var0.put(ModelLayers.WARDEN_HEART, WardenModel.createHeartLayer());
      var0.put(ModelLayers.WARDEN_BIOLUMINESCENT, WardenModel.createBioluminescentLayer());
      var0.put(ModelLayers.WARDEN_PULSATING_SPOTS, WardenModel.createPulsatingSpotsLayer());
      var0.put(ModelLayers.WARM_COW, var49);
      var0.put(ModelLayers.WARM_COW_BABY, var49.apply(CowModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.WANDERING_TRADER, var34);
      var0.put(ModelLayers.WIND_CHARGE, WindChargeModel.createBodyLayer());
      var0.put(ModelLayers.WITCH, WitchModel.createBodyLayer().apply(var13));
      var0.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
      var0.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
      var0.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
      MeshTransformer var65 = MeshTransformer.scaling(1.2F);
      var0.put(ModelLayers.WITHER_SKELETON, var33.apply(var65));
      ModelLayers.WITHER_SKELETON_ARMOR.putFrom(var2.map((var1x) -> var1x.apply(var65)), var0);
      var0.put(ModelLayers.WITHER_SKELETON_SKULL, var8);
      var0.put(ModelLayers.WOLF, var50);
      var0.put(ModelLayers.WOLF_ARMOR, var51);
      var0.put(ModelLayers.WOLF_BABY, var50.apply(WolfModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.WOLF_BABY_ARMOR, var51.apply(WolfModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.ZOGLIN, var31);
      var0.put(ModelLayers.ZOGLIN_BABY, var32);
      var0.put(ModelLayers.ZOMBIE, var1);
      ModelLayers.ZOMBIE_ARMOR.putFrom(var2, var0);
      var0.put(ModelLayers.ZOMBIE_BABY, var1.apply(HumanoidModel.BABY_TRANSFORMER));
      ModelLayers.ZOMBIE_BABY_ARMOR.putFrom(var3, var0);
      var0.put(ModelLayers.ZOMBIE_HEAD, var27);
      var0.put(ModelLayers.ZOMBIE_HORSE, var9);
      var0.put(ModelLayers.ZOMBIE_HORSE_BABY, var10);
      var0.put(ModelLayers.ZOMBIE_HORSE_SADDLE, var11);
      var0.put(ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, var12);
      var0.put(ModelLayers.ZOMBIE_VILLAGER, var52);
      var0.put(ModelLayers.ZOMBIE_VILLAGER_NO_HAT, var53);
      ArmorModelSet var66 = ZombieVillagerModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
      ModelLayers.ZOMBIE_VILLAGER_ARMOR.putFrom(var66, var0);
      var0.put(ModelLayers.ZOMBIE_VILLAGER_BABY, var52.apply(HumanoidModel.BABY_TRANSFORMER));
      var0.put(ModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, var53.apply(HumanoidModel.BABY_TRANSFORMER));
      ModelLayers.ZOMBIE_VILLAGER_BABY_ARMOR.putFrom(var66.map((var0x) -> var0x.apply(HumanoidModel.BABY_TRANSFORMER)), var0);
      var0.put(ModelLayers.ZOMBIFIED_PIGLIN, var25);
      ModelLayers.ZOMBIFIED_PIGLIN_ARMOR.putFrom(var5, var0);
      var0.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY, var25.apply(HumanoidModel.BABY_TRANSFORMER));
      ModelLayers.ZOMBIFIED_PIGLIN_BABY_ARMOR.putFrom(var6, var0);
      var0.put(ModelLayers.BAMBOO_RAFT, RaftModel.createRaftModel());
      var0.put(ModelLayers.BAMBOO_CHEST_RAFT, RaftModel.createChestRaftModel());
      LayerDefinition var67 = BoatModel.createBoatModel();
      LayerDefinition var68 = BoatModel.createChestBoatModel();
      var0.put(ModelLayers.OAK_BOAT, var67);
      var0.put(ModelLayers.OAK_CHEST_BOAT, var68);
      var0.put(ModelLayers.SPRUCE_BOAT, var67);
      var0.put(ModelLayers.SPRUCE_CHEST_BOAT, var68);
      var0.put(ModelLayers.BIRCH_BOAT, var67);
      var0.put(ModelLayers.BIRCH_CHEST_BOAT, var68);
      var0.put(ModelLayers.JUNGLE_BOAT, var67);
      var0.put(ModelLayers.JUNGLE_CHEST_BOAT, var68);
      var0.put(ModelLayers.ACACIA_BOAT, var67);
      var0.put(ModelLayers.ACACIA_CHEST_BOAT, var68);
      var0.put(ModelLayers.CHERRY_BOAT, var67);
      var0.put(ModelLayers.CHERRY_CHEST_BOAT, var68);
      var0.put(ModelLayers.DARK_OAK_BOAT, var67);
      var0.put(ModelLayers.DARK_OAK_CHEST_BOAT, var68);
      var0.put(ModelLayers.PALE_OAK_BOAT, var67);
      var0.put(ModelLayers.PALE_OAK_CHEST_BOAT, var68);
      var0.put(ModelLayers.MANGROVE_BOAT, var67);
      var0.put(ModelLayers.MANGROVE_CHEST_BOAT, var68);
      LayerDefinition var69 = SignRenderer.createSignLayer(true);
      LayerDefinition var70 = SignRenderer.createSignLayer(false);
      WoodType.values().forEach((var3x) -> {
         var0.put(ModelLayers.createStandingSignModelName(var3x), var69);
         var0.put(ModelLayers.createWallSignModelName(var3x), var70);

         for(HangingSignRenderer.AttachmentType var7 : HangingSignRenderer.AttachmentType.values()) {
            LayerDefinition var8 = HangingSignRenderer.createHangingSignLayer(var7);
            var0.put(ModelLayers.createHangingSignModelName(var3x, var7), var8);
         }

      });
      ImmutableMap var71 = var0.build();
      List var72 = ModelLayers.getKnownLocations().filter((var1x) -> !var71.containsKey(var1x)).toList();
      if (!var72.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + String.valueOf(var72));
      } else {
         return var71;
      }
   }
}
