package net.minecraft.client.gui.render;

public enum GuiLayer {
   GAMEPLAY_OVERLAY,
   HUD,
   HUD_ITEM,
   HUD_ITEM_COUNT,
   HUD_ITEM_DECORATION,
   SLEEP_OVERLAY,
   DEMO_OVERLAY,
   DEBUG_OVERLAY,
   DEBUG_OVERLAY_PROFILER_CHART,
   SCOREBOARD_OVERLAY,
   OVERLAY_MESSAGE,
   TITLE_OVERLAY,
   CHAT_OVERLAY,
   TABLIST_OVERLAY,
   SUBTITLE_OVERLAY,
   PANORAMA,
   SCREEN_BACKGROUND,
   SCREEN_ADVANCEMENT_CONTENT,
   SCREEN,
   SCREEN_CHAT,
   SCREEN_CHAT_TEXT,
   SCREEN_WIDGET_TEXT,
   SCREEN_POPUP,
   TITLE_SCREEN_JAVA_EDITION,
   SCREEN_MAP_DECORATION,
   SCREEN_TEXT_HIGHLIGHT,
   SCREEN_SLOT_HIGHLIGHT_BACK,
   SCREEN_SLOT_HIGHLIGHT_BACK_GHOST,
   SCREEN_SLOT,
   SCREEN_SLOT_COUNT,
   SCREEN_SLOT_DECORATION,
   SCREEN_SLOT_HIGHLIGHT_FRONT,
   SCREEN_SLOT_HIGHLIGHT_FRONT_GHOST,
   SCREEN_SLOT_ICON_ABOVE_HIGHLIGHT,
   SCREEN_TOOLTIP,
   LOADING_OVERLAY,
   MOJANG_LOGO;

   private GuiLayer() {
   }

   // $FF: synthetic method
   private static GuiLayer[] $values() {
      return new GuiLayer[]{GAMEPLAY_OVERLAY, HUD, HUD_ITEM, HUD_ITEM_COUNT, HUD_ITEM_DECORATION, SLEEP_OVERLAY, DEMO_OVERLAY, DEBUG_OVERLAY, DEBUG_OVERLAY_PROFILER_CHART, SCOREBOARD_OVERLAY, OVERLAY_MESSAGE, TITLE_OVERLAY, CHAT_OVERLAY, TABLIST_OVERLAY, SUBTITLE_OVERLAY, PANORAMA, SCREEN_BACKGROUND, SCREEN_ADVANCEMENT_CONTENT, SCREEN, SCREEN_CHAT, SCREEN_CHAT_TEXT, SCREEN_WIDGET_TEXT, SCREEN_POPUP, TITLE_SCREEN_JAVA_EDITION, SCREEN_MAP_DECORATION, SCREEN_TEXT_HIGHLIGHT, SCREEN_SLOT_HIGHLIGHT_BACK, SCREEN_SLOT_HIGHLIGHT_BACK_GHOST, SCREEN_SLOT, SCREEN_SLOT_COUNT, SCREEN_SLOT_DECORATION, SCREEN_SLOT_HIGHLIGHT_FRONT, SCREEN_SLOT_HIGHLIGHT_FRONT_GHOST, SCREEN_SLOT_ICON_ABOVE_HIGHLIGHT, SCREEN_TOOLTIP, LOADING_OVERLAY, MOJANG_LOGO};
   }
}
