package net.minecraft.util.datafix;

import com.google.common.collect.ImmutableMap;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFixer;
import com.mojang.datafixers.DataFixerBuilder;
import com.mojang.datafixers.Typed;
import com.mojang.datafixers.schemas.Schema;
import java.util.Objects;
import java.util.function.BiFunction;
import net.minecraft.SharedConstants;
import net.minecraft.Util;
import net.minecraft.util.datafix.fixes.AddNewChoices;
import net.minecraft.util.datafix.fixes.AdvancementsFix;
import net.minecraft.util.datafix.fixes.BedBlockEntityInjecter;
import net.minecraft.util.datafix.fixes.BedItemColorFix;
import net.minecraft.util.datafix.fixes.BeehivePoiRenameFix;
import net.minecraft.util.datafix.fixes.BiomeFix;
import net.minecraft.util.datafix.fixes.BlockEntityBannerColorFix;
import net.minecraft.util.datafix.fixes.BlockEntityBlockStateFix;
import net.minecraft.util.datafix.fixes.BlockEntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.BlockEntityIdFix;
import net.minecraft.util.datafix.fixes.BlockEntityJukeboxFix;
import net.minecraft.util.datafix.fixes.BlockEntityKeepPacked;
import net.minecraft.util.datafix.fixes.BlockEntityShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.BlockEntitySignTextStrictJsonFix;
import net.minecraft.util.datafix.fixes.BlockNameFlatteningFix;
import net.minecraft.util.datafix.fixes.BlockRenameFix;
import net.minecraft.util.datafix.fixes.BlockStateStructureTemplateFix;
import net.minecraft.util.datafix.fixes.CatTypeFix;
import net.minecraft.util.datafix.fixes.ChunkBiomeFix;
import net.minecraft.util.datafix.fixes.ChunkLightRemoveFix;
import net.minecraft.util.datafix.fixes.ChunkPalettedStorageFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix2;
import net.minecraft.util.datafix.fixes.ChunkStructuresTemplateRenameFix;
import net.minecraft.util.datafix.fixes.ChunkToProtochunkFix;
import net.minecraft.util.datafix.fixes.ColorlessShulkerEntityFix;
import net.minecraft.util.datafix.fixes.DyeItemRenameFix;
import net.minecraft.util.datafix.fixes.EntityArmorStandSilentFix;
import net.minecraft.util.datafix.fixes.EntityBlockStateFix;
import net.minecraft.util.datafix.fixes.EntityCatSplitFix;
import net.minecraft.util.datafix.fixes.EntityCodSalmonFix;
import net.minecraft.util.datafix.fixes.EntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.EntityElderGuardianSplitFix;
import net.minecraft.util.datafix.fixes.EntityEquipmentToArmorAndHandFix;
import net.minecraft.util.datafix.fixes.EntityHealthFix;
import net.minecraft.util.datafix.fixes.EntityHorseSaddleFix;
import net.minecraft.util.datafix.fixes.EntityHorseSplitFix;
import net.minecraft.util.datafix.fixes.EntityIdFix;
import net.minecraft.util.datafix.fixes.EntityItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityMinecartIdentifiersFix;
import net.minecraft.util.datafix.fixes.EntityPaintingItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityPaintingMotiveFix;
import net.minecraft.util.datafix.fixes.EntityPufferfishRenameFix;
import net.minecraft.util.datafix.fixes.EntityRavagerRenameFix;
import net.minecraft.util.datafix.fixes.EntityRedundantChanceTagsFix;
import net.minecraft.util.datafix.fixes.EntityRidingToPassengersFix;
import net.minecraft.util.datafix.fixes.EntityShulkerColorFix;
import net.minecraft.util.datafix.fixes.EntitySkeletonSplitFix;
import net.minecraft.util.datafix.fixes.EntityStringUuidFix;
import net.minecraft.util.datafix.fixes.EntityTheRenameningFix;
import net.minecraft.util.datafix.fixes.EntityTippedArrowFix;
import net.minecraft.util.datafix.fixes.EntityWolfColorFix;
import net.minecraft.util.datafix.fixes.EntityZombieSplitFix;
import net.minecraft.util.datafix.fixes.EntityZombieVillagerTypeFix;
import net.minecraft.util.datafix.fixes.ForcePoiRebuild;
import net.minecraft.util.datafix.fixes.HeightmapRenamingFix;
import net.minecraft.util.datafix.fixes.IglooMetadataRemovalFix;
import net.minecraft.util.datafix.fixes.ItemBannerColorFix;
import net.minecraft.util.datafix.fixes.ItemCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.ItemIdFix;
import net.minecraft.util.datafix.fixes.ItemLoreFix;
import net.minecraft.util.datafix.fixes.ItemPotionFix;
import net.minecraft.util.datafix.fixes.ItemRenameFix;
import net.minecraft.util.datafix.fixes.ItemShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.ItemSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackEnchantmentNamesFix;
import net.minecraft.util.datafix.fixes.ItemStackMapIdFix;
import net.minecraft.util.datafix.fixes.ItemStackSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackTheFlatteningFix;
import net.minecraft.util.datafix.fixes.ItemWaterPotionFix;
import net.minecraft.util.datafix.fixes.ItemWrittenBookPagesStrictJsonFix;
import net.minecraft.util.datafix.fixes.LeavesFix;
import net.minecraft.util.datafix.fixes.LevelDataGeneratorOptionsFix;
import net.minecraft.util.datafix.fixes.LevelFlatGeneratorInfoFix;
import net.minecraft.util.datafix.fixes.MapIdFix;
import net.minecraft.util.datafix.fixes.MobSpawnerEntityIdentifiersFix;
import net.minecraft.util.datafix.fixes.NamedEntityFix;
import net.minecraft.util.datafix.fixes.NewVillageFix;
import net.minecraft.util.datafix.fixes.ObjectiveDisplayNameFix;
import net.minecraft.util.datafix.fixes.ObjectiveRenderTypeFix;
import net.minecraft.util.datafix.fixes.OptionsAddTextBackgroundFix;
import net.minecraft.util.datafix.fixes.OptionsForceVBOFix;
import net.minecraft.util.datafix.fixes.OptionsKeyLwjgl3Fix;
import net.minecraft.util.datafix.fixes.OptionsKeyTranslationFix;
import net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguageFix;
import net.minecraft.util.datafix.fixes.RecipesFix;
import net.minecraft.util.datafix.fixes.RecipesRenameningFix;
import net.minecraft.util.datafix.fixes.References;
import net.minecraft.util.datafix.fixes.RenamedCoralFansFix;
import net.minecraft.util.datafix.fixes.RenamedCoralFix;
import net.minecraft.util.datafix.fixes.ReorganizePoi;
import net.minecraft.util.datafix.fixes.SavedDataVillageCropFix;
import net.minecraft.util.datafix.fixes.StatsCounterFix;
import net.minecraft.util.datafix.fixes.StructureReferenceCountFix;
import net.minecraft.util.datafix.fixes.SwimStatsRenameFix;
import net.minecraft.util.datafix.fixes.TeamDisplayNameFix;
import net.minecraft.util.datafix.fixes.TrappedChestBlockEntityFix;
import net.minecraft.util.datafix.fixes.VillagerDataFix;
import net.minecraft.util.datafix.fixes.VillagerRebuildLevelAndXpFix;
import net.minecraft.util.datafix.fixes.VillagerTradeFix;
import net.minecraft.util.datafix.fixes.WriteAndReadFix;
import net.minecraft.util.datafix.fixes.ZombieVillagerRebuildXpFix;
import net.minecraft.util.datafix.schemas.NamespacedSchema;
import net.minecraft.util.datafix.schemas.V100;
import net.minecraft.util.datafix.schemas.V102;
import net.minecraft.util.datafix.schemas.V1022;
import net.minecraft.util.datafix.schemas.V106;
import net.minecraft.util.datafix.schemas.V107;
import net.minecraft.util.datafix.schemas.V1125;
import net.minecraft.util.datafix.schemas.V135;
import net.minecraft.util.datafix.schemas.V143;
import net.minecraft.util.datafix.schemas.V1451;
import net.minecraft.util.datafix.schemas.V1451_1;
import net.minecraft.util.datafix.schemas.V1451_2;
import net.minecraft.util.datafix.schemas.V1451_3;
import net.minecraft.util.datafix.schemas.V1451_4;
import net.minecraft.util.datafix.schemas.V1451_5;
import net.minecraft.util.datafix.schemas.V1451_6;
import net.minecraft.util.datafix.schemas.V1451_7;
import net.minecraft.util.datafix.schemas.V1460;
import net.minecraft.util.datafix.schemas.V1466;
import net.minecraft.util.datafix.schemas.V1470;
import net.minecraft.util.datafix.schemas.V1481;
import net.minecraft.util.datafix.schemas.V1483;
import net.minecraft.util.datafix.schemas.V1486;
import net.minecraft.util.datafix.schemas.V1510;
import net.minecraft.util.datafix.schemas.V1800;
import net.minecraft.util.datafix.schemas.V1801;
import net.minecraft.util.datafix.schemas.V1904;
import net.minecraft.util.datafix.schemas.V1906;
import net.minecraft.util.datafix.schemas.V1909;
import net.minecraft.util.datafix.schemas.V1920;
import net.minecraft.util.datafix.schemas.V1928;
import net.minecraft.util.datafix.schemas.V1929;
import net.minecraft.util.datafix.schemas.V1931;
import net.minecraft.util.datafix.schemas.V2100;
import net.minecraft.util.datafix.schemas.V501;
import net.minecraft.util.datafix.schemas.V700;
import net.minecraft.util.datafix.schemas.V701;
import net.minecraft.util.datafix.schemas.V702;
import net.minecraft.util.datafix.schemas.V703;
import net.minecraft.util.datafix.schemas.V704;
import net.minecraft.util.datafix.schemas.V705;
import net.minecraft.util.datafix.schemas.V808;
import net.minecraft.util.datafix.schemas.V99;

public class DataFixers {
   private static final BiFunction SAME = Schema::new;
   private static final BiFunction SAME_NAMESPACED = NamespacedSchema::new;
   private static final DataFixer DATA_FIXER = createFixerUpper();

   private static DataFixer createFixerUpper() {
      DataFixerBuilder var0 = new DataFixerBuilder(SharedConstants.getCurrentVersion().getWorldVersion());
      addFixers(var0);
      return var0.build(Util.backgroundExecutor());
   }

   public static DataFixer getDataFixer() {
      return DATA_FIXER;
   }

   private static void addFixers(DataFixerBuilder var0) {
      Schema var1 = var0.addSchema(99, V99::new);
      Schema var2 = var0.addSchema(100, V100::new);
      var0.addFixer(new EntityEquipmentToArmorAndHandFix(var2, true));
      Schema var3 = var0.addSchema(101, SAME);
      var0.addFixer(new BlockEntitySignTextStrictJsonFix(var3, false));
      Schema var4 = var0.addSchema(102, V102::new);
      var0.addFixer(new ItemIdFix(var4, true));
      var0.addFixer(new ItemPotionFix(var4, false));
      Schema var5 = var0.addSchema(105, SAME);
      var0.addFixer(new ItemSpawnEggFix(var5, true));
      Schema var6 = var0.addSchema(106, V106::new);
      var0.addFixer(new MobSpawnerEntityIdentifiersFix(var6, true));
      Schema var7 = var0.addSchema(107, V107::new);
      var0.addFixer(new EntityMinecartIdentifiersFix(var7, true));
      Schema var8 = var0.addSchema(108, SAME);
      var0.addFixer(new EntityStringUuidFix(var8, true));
      Schema var9 = var0.addSchema(109, SAME);
      var0.addFixer(new EntityHealthFix(var9, true));
      Schema var10 = var0.addSchema(110, SAME);
      var0.addFixer(new EntityHorseSaddleFix(var10, true));
      Schema var11 = var0.addSchema(111, SAME);
      var0.addFixer(new EntityPaintingItemFrameDirectionFix(var11, true));
      Schema var12 = var0.addSchema(113, SAME);
      var0.addFixer(new EntityRedundantChanceTagsFix(var12, true));
      Schema var13 = var0.addSchema(135, V135::new);
      var0.addFixer(new EntityRidingToPassengersFix(var13, true));
      Schema var14 = var0.addSchema(143, V143::new);
      var0.addFixer(new EntityTippedArrowFix(var14, true));
      Schema var15 = var0.addSchema(147, SAME);
      var0.addFixer(new EntityArmorStandSilentFix(var15, true));
      Schema var16 = var0.addSchema(165, SAME);
      var0.addFixer(new ItemWrittenBookPagesStrictJsonFix(var16, true));
      Schema var17 = var0.addSchema(501, V501::new);
      var0.addFixer(new AddNewChoices(var17, "Add 1.10 entities fix", References.ENTITY));
      Schema var18 = var0.addSchema(502, SAME);
      var0.addFixer(ItemRenameFix.create(var18, "cooked_fished item renamer", (var0x) -> {
         return Objects.equals(NamespacedSchema.ensureNamespaced(var0x), "minecraft:cooked_fished") ? "minecraft:cooked_fish" : var0x;
      }));
      var0.addFixer(new EntityZombieVillagerTypeFix(var18, false));
      Schema var19 = var0.addSchema(505, SAME);
      var0.addFixer(new OptionsForceVBOFix(var19, false));
      Schema var20 = var0.addSchema(700, V700::new);
      var0.addFixer(new EntityElderGuardianSplitFix(var20, true));
      Schema var21 = var0.addSchema(701, V701::new);
      var0.addFixer(new EntitySkeletonSplitFix(var21, true));
      Schema var22 = var0.addSchema(702, V702::new);
      var0.addFixer(new EntityZombieSplitFix(var22, true));
      Schema var23 = var0.addSchema(703, V703::new);
      var0.addFixer(new EntityHorseSplitFix(var23, true));
      Schema var24 = var0.addSchema(704, V704::new);
      var0.addFixer(new BlockEntityIdFix(var24, true));
      Schema var25 = var0.addSchema(705, V705::new);
      var0.addFixer(new EntityIdFix(var25, true));
      Schema var26 = var0.addSchema(804, SAME_NAMESPACED);
      var0.addFixer(new ItemBannerColorFix(var26, true));
      Schema var27 = var0.addSchema(806, SAME_NAMESPACED);
      var0.addFixer(new ItemWaterPotionFix(var27, false));
      Schema var28 = var0.addSchema(808, V808::new);
      var0.addFixer(new AddNewChoices(var28, "added shulker box", References.BLOCK_ENTITY));
      Schema var29 = var0.addSchema(808, 1, SAME_NAMESPACED);
      var0.addFixer(new EntityShulkerColorFix(var29, false));
      Schema var30 = var0.addSchema(813, SAME_NAMESPACED);
      var0.addFixer(new ItemShulkerBoxColorFix(var30, false));
      var0.addFixer(new BlockEntityShulkerBoxColorFix(var30, false));
      Schema var31 = var0.addSchema(816, SAME_NAMESPACED);
      var0.addFixer(new OptionsLowerCaseLanguageFix(var31, false));
      Schema var32 = var0.addSchema(820, SAME_NAMESPACED);
      var0.addFixer(ItemRenameFix.create(var32, "totem item renamer", (var0x) -> {
         return Objects.equals(var0x, "minecraft:totem") ? "minecraft:totem_of_undying" : var0x;
      }));
      Schema var33 = var0.addSchema(1022, V1022::new);
      var0.addFixer(new WriteAndReadFix(var33, "added shoulder entities to players", References.PLAYER));
      Schema var34 = var0.addSchema(1125, V1125::new);
      var0.addFixer(new BedBlockEntityInjecter(var34, true));
      var0.addFixer(new BedItemColorFix(var34, false));
      Schema var35 = var0.addSchema(1344, SAME_NAMESPACED);
      var0.addFixer(new OptionsKeyLwjgl3Fix(var35, false));
      Schema var36 = var0.addSchema(1446, SAME_NAMESPACED);
      var0.addFixer(new OptionsKeyTranslationFix(var36, false));
      Schema var37 = var0.addSchema(1450, SAME_NAMESPACED);
      var0.addFixer(new BlockStateStructureTemplateFix(var37, false));
      Schema var38 = var0.addSchema(1451, V1451::new);
      var0.addFixer(new AddNewChoices(var38, "AddTrappedChestFix", References.BLOCK_ENTITY));
      Schema var39 = var0.addSchema(1451, 1, V1451_1::new);
      var0.addFixer(new ChunkPalettedStorageFix(var39, true));
      Schema var40 = var0.addSchema(1451, 2, V1451_2::new);
      var0.addFixer(new BlockEntityBlockStateFix(var40, true));
      Schema var41 = var0.addSchema(1451, 3, V1451_3::new);
      var0.addFixer(new EntityBlockStateFix(var41, true));
      var0.addFixer(new ItemStackMapIdFix(var41, false));
      Schema var42 = var0.addSchema(1451, 4, V1451_4::new);
      var0.addFixer(new BlockNameFlatteningFix(var42, true));
      var0.addFixer(new ItemStackTheFlatteningFix(var42, false));
      Schema var43 = var0.addSchema(1451, 5, V1451_5::new);
      var0.addFixer(new AddNewChoices(var43, "RemoveNoteBlockFlowerPotFix", References.BLOCK_ENTITY));
      var0.addFixer(new ItemStackSpawnEggFix(var43, false));
      var0.addFixer(new EntityWolfColorFix(var43, false));
      var0.addFixer(new BlockEntityBannerColorFix(var43, false));
      var0.addFixer(new LevelFlatGeneratorInfoFix(var43, false));
      Schema var44 = var0.addSchema(1451, 6, V1451_6::new);
      var0.addFixer(new StatsCounterFix(var44, true));
      var0.addFixer(new BlockEntityJukeboxFix(var44, false));
      Schema var45 = var0.addSchema(1451, 7, V1451_7::new);
      var0.addFixer(new SavedDataVillageCropFix(var45, true));
      Schema var46 = var0.addSchema(1451, 7, SAME_NAMESPACED);
      var0.addFixer(new VillagerTradeFix(var46, false));
      Schema var47 = var0.addSchema(1456, SAME_NAMESPACED);
      var0.addFixer(new EntityItemFrameDirectionFix(var47, false));
      Schema var48 = var0.addSchema(1458, SAME_NAMESPACED);
      var0.addFixer(new EntityCustomNameToComponentFix(var48, false));
      var0.addFixer(new ItemCustomNameToComponentFix(var48, false));
      var0.addFixer(new BlockEntityCustomNameToComponentFix(var48, false));
      Schema var49 = var0.addSchema(1460, V1460::new);
      var0.addFixer(new EntityPaintingMotiveFix(var49, false));
      Schema var50 = var0.addSchema(1466, V1466::new);
      var0.addFixer(new ChunkToProtochunkFix(var50, true));
      Schema var51 = var0.addSchema(1470, V1470::new);
      var0.addFixer(new AddNewChoices(var51, "Add 1.13 entities fix", References.ENTITY));
      Schema var52 = var0.addSchema(1474, SAME_NAMESPACED);
      var0.addFixer(new ColorlessShulkerEntityFix(var52, false));
      var0.addFixer(BlockRenameFix.create(var52, "Colorless shulker block fixer", (var0x) -> {
         return Objects.equals(NamespacedSchema.ensureNamespaced(var0x), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : var0x;
      }));
      var0.addFixer(ItemRenameFix.create(var52, "Colorless shulker item fixer", (var0x) -> {
         return Objects.equals(NamespacedSchema.ensureNamespaced(var0x), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : var0x;
      }));
      Schema var53 = var0.addSchema(1475, SAME_NAMESPACED);
      var0.addFixer(BlockRenameFix.create(var53, "Flowing fixer", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:flowing_water", "minecraft:water", "minecraft:flowing_lava", "minecraft:lava").getOrDefault(var0x, var0x);
      }));
      Schema var54 = var0.addSchema(1480, SAME_NAMESPACED);
      var0.addFixer(BlockRenameFix.create(var54, "Rename coral blocks", (var0x) -> {
         return (String)RenamedCoralFix.RENAMED_IDS.getOrDefault(var0x, var0x);
      }));
      var0.addFixer(ItemRenameFix.create(var54, "Rename coral items", (var0x) -> {
         return (String)RenamedCoralFix.RENAMED_IDS.getOrDefault(var0x, var0x);
      }));
      Schema var55 = var0.addSchema(1481, V1481::new);
      var0.addFixer(new AddNewChoices(var55, "Add conduit", References.BLOCK_ENTITY));
      Schema var56 = var0.addSchema(1483, V1483::new);
      var0.addFixer(new EntityPufferfishRenameFix(var56, true));
      var0.addFixer(ItemRenameFix.create(var56, "Rename pufferfish egg item", (var0x) -> {
         return (String)EntityPufferfishRenameFix.RENAMED_IDS.getOrDefault(var0x, var0x);
      }));
      Schema var57 = var0.addSchema(1484, SAME_NAMESPACED);
      var0.addFixer(ItemRenameFix.create(var57, "Rename seagrass items", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass").getOrDefault(var0x, var0x);
      }));
      var0.addFixer(BlockRenameFix.create(var57, "Rename seagrass blocks", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass").getOrDefault(var0x, var0x);
      }));
      var0.addFixer(new HeightmapRenamingFix(var57, false));
      Schema var58 = var0.addSchema(1486, V1486::new);
      var0.addFixer(new EntityCodSalmonFix(var58, true));
      var0.addFixer(ItemRenameFix.create(var58, "Rename cod/salmon egg items", (var0x) -> {
         return (String)EntityCodSalmonFix.RENAMED_EGG_IDS.getOrDefault(var0x, var0x);
      }));
      Schema var59 = var0.addSchema(1487, SAME_NAMESPACED);
      var0.addFixer(ItemRenameFix.create(var59, "Rename prismarine_brick(s)_* blocks", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs").getOrDefault(var0x, var0x);
      }));
      var0.addFixer(BlockRenameFix.create(var59, "Rename prismarine_brick(s)_* items", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs").getOrDefault(var0x, var0x);
      }));
      Schema var60 = var0.addSchema(1488, SAME_NAMESPACED);
      var0.addFixer(BlockRenameFix.create(var60, "Rename kelp/kelptop", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:kelp_top", "minecraft:kelp", "minecraft:kelp", "minecraft:kelp_plant").getOrDefault(var0x, var0x);
      }));
      var0.addFixer(ItemRenameFix.create(var60, "Rename kelptop", (var0x) -> {
         return Objects.equals(var0x, "minecraft:kelp_top") ? "minecraft:kelp" : var0x;
      }));
      var0.addFixer(new NamedEntityFix(var60, false, "Command block block entity custom name fix", References.BLOCK_ENTITY, "minecraft:command_block") {
         protected Typed fix(Typed var1) {
            return var1.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::fixTagCustomName);
         }
      });
      var0.addFixer(new NamedEntityFix(var60, false, "Command block minecart custom name fix", References.ENTITY, "minecraft:commandblock_minecart") {
         protected Typed fix(Typed var1) {
            return var1.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::fixTagCustomName);
         }
      });
      var0.addFixer(new IglooMetadataRemovalFix(var60, false));
      Schema var61 = var0.addSchema(1490, SAME_NAMESPACED);
      var0.addFixer(BlockRenameFix.create(var61, "Rename melon_block", (var0x) -> {
         return Objects.equals(var0x, "minecraft:melon_block") ? "minecraft:melon" : var0x;
      }));
      var0.addFixer(ItemRenameFix.create(var61, "Rename melon_block/melon/speckled_melon", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:melon_block", "minecraft:melon", "minecraft:melon", "minecraft:melon_slice", "minecraft:speckled_melon", "minecraft:glistering_melon_slice").getOrDefault(var0x, var0x);
      }));
      Schema var62 = var0.addSchema(1492, SAME_NAMESPACED);
      var0.addFixer(new ChunkStructuresTemplateRenameFix(var62, false));
      Schema var63 = var0.addSchema(1494, SAME_NAMESPACED);
      var0.addFixer(new ItemStackEnchantmentNamesFix(var63, false));
      Schema var64 = var0.addSchema(1496, SAME_NAMESPACED);
      var0.addFixer(new LeavesFix(var64, false));
      Schema var65 = var0.addSchema(1500, SAME_NAMESPACED);
      var0.addFixer(new BlockEntityKeepPacked(var65, false));
      Schema var66 = var0.addSchema(1501, SAME_NAMESPACED);
      var0.addFixer(new AdvancementsFix(var66, false));
      Schema var67 = var0.addSchema(1502, SAME_NAMESPACED);
      var0.addFixer(new RecipesFix(var67, false));
      Schema var68 = var0.addSchema(1506, SAME_NAMESPACED);
      var0.addFixer(new LevelDataGeneratorOptionsFix(var68, false));
      Schema var69 = var0.addSchema(1508, SAME_NAMESPACED);
      var0.addFixer(new BiomeFix(var69, false));
      Schema var70 = var0.addSchema(1510, V1510::new);
      var0.addFixer(BlockRenameFix.create(var70, "Block renamening fix", (var0x) -> {
         return (String)EntityTheRenameningFix.RENAMED_BLOCKS.getOrDefault(var0x, var0x);
      }));
      var0.addFixer(ItemRenameFix.create(var70, "Item renamening fix", (var0x) -> {
         return (String)EntityTheRenameningFix.RENAMED_ITEMS.getOrDefault(var0x, var0x);
      }));
      var0.addFixer(new RecipesRenameningFix(var70, false));
      var0.addFixer(new EntityTheRenameningFix(var70, true));
      var0.addFixer(new SwimStatsRenameFix(var70, false));
      Schema var71 = var0.addSchema(1514, SAME_NAMESPACED);
      var0.addFixer(new ObjectiveDisplayNameFix(var71, false));
      var0.addFixer(new TeamDisplayNameFix(var71, false));
      var0.addFixer(new ObjectiveRenderTypeFix(var71, false));
      Schema var72 = var0.addSchema(1515, SAME_NAMESPACED);
      var0.addFixer(BlockRenameFix.create(var72, "Rename coral fan blocks", (var0x) -> {
         return (String)RenamedCoralFansFix.RENAMED_IDS.getOrDefault(var0x, var0x);
      }));
      Schema var73 = var0.addSchema(1624, SAME_NAMESPACED);
      var0.addFixer(new TrappedChestBlockEntityFix(var73, false));
      Schema var74 = var0.addSchema(1800, V1800::new);
      var0.addFixer(new AddNewChoices(var74, "Added 1.14 mobs fix", References.ENTITY));
      var0.addFixer(ItemRenameFix.create(var74, "Rename dye items", (var0x) -> {
         return (String)DyeItemRenameFix.RENAMED_IDS.getOrDefault(var0x, var0x);
      }));
      Schema var75 = var0.addSchema(1801, V1801::new);
      var0.addFixer(new AddNewChoices(var75, "Added Illager Beast", References.ENTITY));
      Schema var76 = var0.addSchema(1802, SAME_NAMESPACED);
      var0.addFixer(BlockRenameFix.create(var76, "Rename sign blocks & stone slabs", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign", "minecraft:wall_sign", "minecraft:oak_wall_sign").getOrDefault(var0x, var0x);
      }));
      var0.addFixer(ItemRenameFix.create(var76, "Rename sign item & stone slabs", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign").getOrDefault(var0x, var0x);
      }));
      Schema var77 = var0.addSchema(1803, SAME_NAMESPACED);
      var0.addFixer(new ItemLoreFix(var77, false));
      Schema var78 = var0.addSchema(1904, V1904::new);
      var0.addFixer(new AddNewChoices(var78, "Added Cats", References.ENTITY));
      var0.addFixer(new EntityCatSplitFix(var78, false));
      Schema var79 = var0.addSchema(1905, SAME_NAMESPACED);
      var0.addFixer(new ChunkStatusFix(var79, false));
      Schema var80 = var0.addSchema(1906, V1906::new);
      var0.addFixer(new AddNewChoices(var80, "Add POI Blocks", References.BLOCK_ENTITY));
      Schema var81 = var0.addSchema(1909, V1909::new);
      var0.addFixer(new AddNewChoices(var81, "Add jigsaw", References.BLOCK_ENTITY));
      Schema var82 = var0.addSchema(1911, SAME_NAMESPACED);
      var0.addFixer(new ChunkStatusFix2(var82, false));
      Schema var83 = var0.addSchema(1917, SAME_NAMESPACED);
      var0.addFixer(new CatTypeFix(var83, false));
      Schema var84 = var0.addSchema(1918, SAME_NAMESPACED);
      var0.addFixer(new VillagerDataFix(var84, "minecraft:villager"));
      var0.addFixer(new VillagerDataFix(var84, "minecraft:zombie_villager"));
      Schema var85 = var0.addSchema(1920, V1920::new);
      var0.addFixer(new NewVillageFix(var85, false));
      var0.addFixer(new AddNewChoices(var85, "Add campfire", References.BLOCK_ENTITY));
      Schema var86 = var0.addSchema(1925, SAME_NAMESPACED);
      var0.addFixer(new MapIdFix(var86, false));
      Schema var87 = var0.addSchema(1928, V1928::new);
      var0.addFixer(new EntityRavagerRenameFix(var87, true));
      var0.addFixer(ItemRenameFix.create(var87, "Rename ravager egg item", (var0x) -> {
         return (String)EntityRavagerRenameFix.RENAMED_IDS.getOrDefault(var0x, var0x);
      }));
      Schema var88 = var0.addSchema(1929, V1929::new);
      var0.addFixer(new AddNewChoices(var88, "Add Wandering Trader and Trader Llama", References.ENTITY));
      Schema var89 = var0.addSchema(1931, V1931::new);
      var0.addFixer(new AddNewChoices(var89, "Added Fox", References.ENTITY));
      Schema var90 = var0.addSchema(1936, SAME_NAMESPACED);
      var0.addFixer(new OptionsAddTextBackgroundFix(var90, false));
      Schema var91 = var0.addSchema(1946, SAME_NAMESPACED);
      var0.addFixer(new ReorganizePoi(var91, false));
      Schema var92 = var0.addSchema(1948, SAME_NAMESPACED);
      var0.addFixer(new OminousBannerRenameFix(var92, false));
      Schema var93 = var0.addSchema(1953, SAME_NAMESPACED);
      var0.addFixer(new OminousBannerBlockEntityRenameFix(var93, false));
      Schema var94 = var0.addSchema(1955, SAME_NAMESPACED);
      var0.addFixer(new VillagerRebuildLevelAndXpFix(var94, false));
      var0.addFixer(new ZombieVillagerRebuildXpFix(var94, false));
      Schema var95 = var0.addSchema(1961, SAME_NAMESPACED);
      var0.addFixer(new ChunkLightRemoveFix(var95, false));
      Schema var96 = var0.addSchema(2100, V2100::new);
      var0.addFixer(new AddNewChoices(var96, "Added Bee and Bee Stinger", References.ENTITY));
      var0.addFixer(new AddNewChoices(var96, "Add beehive", References.BLOCK_ENTITY));
      Schema var97 = var0.addSchema(2202, SAME_NAMESPACED);
      var0.addFixer(new ChunkBiomeFix(var97, false));
      Schema var98 = var0.addSchema(2209, SAME_NAMESPACED);
      var0.addFixer(ItemRenameFix.create(var98, "Rename bee_hive item to beehive", (var0x) -> {
         return Objects.equals(var0x, "minecraft:bee_hive") ? "minecraft:beehive" : var0x;
      }));
      var0.addFixer(new BeehivePoiRenameFix(var98));
      var0.addFixer(BlockRenameFix.create(var98, "Rename bee_hive block to beehive", (var0x) -> {
         return (String)ImmutableMap.of("minecraft:bee_hive", "minecraft:beehive").getOrDefault(var0x, var0x);
      }));
      Schema var99 = var0.addSchema(2211, SAME_NAMESPACED);
      var0.addFixer(new StructureReferenceCountFix(var99, false));
      Schema var100 = var0.addSchema(2218, SAME_NAMESPACED);
      var0.addFixer(new ForcePoiRebuild(var100, false));
   }
}
